/*
Generated by:
JavaScript APG, Version 1.0
an ABNF Parser Generator

Copyright (C) 2009 Lowell D. Thomas, all rights reserved

email: lowell@coasttocoastresearch.com
website: http://www.coasttocoastresearch.com

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see
<http://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
or write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
*/
function ABNFOpcodes()
{
    // SUMMARY
    // string table length: 21
    //               rules: 38
    //             opcodes: 197

    // string table
    this.stringTable = [];
    this.stringTable[0] = 58;
    this.stringTable[1] = 61;
    this.stringTable[2] = 61;
    this.stringTable[3] = 61;
    this.stringTable[4] = 60;
    this.stringTable[5] = 60;
    this.stringTable[6] = 60;
    this.stringTable[7] = 43;
    this.stringTable[8] = 124;
    this.stringTable[9] = 124;
    this.stringTable[10] = 44;
    this.stringTable[11] = 123;
    this.stringTable[12] = 125;
    this.stringTable[13] = 44;
    this.stringTable[14] = 61;
    this.stringTable[15] = 35;
    this.stringTable[16] = 40;
    this.stringTable[17] = 41;
    this.stringTable[18] = 45;
    this.stringTable[19] = 43;
    this.stringTable[20] = 46;

    // rule identifiers
    this.ruleIds = [];
    this.ruleIds.expression = 0;
    this.ruleIds.subexpression = 1;
    this.ruleIds.definitionstatus = 2;
    this.ruleIds.equivalentto = 3;
    this.ruleIds.subtypeof = 4;
    this.ruleIds.focusconcept = 5;
    this.ruleIds.conceptreference = 6;
    this.ruleIds.conceptid = 7;
    this.ruleIds.term = 8;
    this.ruleIds.refinement = 9;
    this.ruleIds.attributegroup = 10;
    this.ruleIds.attributeset = 11;
    this.ruleIds.attribute = 12;
    this.ruleIds.attributename = 13;
    this.ruleIds.attributevalue = 14;
    this.ruleIds.expressionvalue = 15;
    this.ruleIds.stringvalue = 16;
    this.ruleIds.numericvalue = 17;
    this.ruleIds.integervalue = 18;
    this.ruleIds.decimalvalue = 19;
    this.ruleIds.sctid = 20;
    this.ruleIds.ws = 21;
    this.ruleIds.sp = 22;
    this.ruleIds.htab = 23;
    this.ruleIds.cr = 24;
    this.ruleIds.lf = 25;
    this.ruleIds.qm = 26;
    this.ruleIds.bs = 27;
    this.ruleIds.digit = 28;
    this.ruleIds.zero = 29;
    this.ruleIds.digitnonzero = 30;
    this.ruleIds.nonwsnonpipe = 31;
    this.ruleIds.anynonescapedchar = 32;
    this.ruleIds.escapedchar = 33;
    this.ruleIds['utf8-2'] = 34;
    this.ruleIds['utf8-3'] = 35;
    this.ruleIds['utf8-4'] = 36;
    this.ruleIds['utf8-tail'] = 37;

    // rule identifiers (alphabetical)
    this.ruleIds[0] = 32; // anyNonEscapedChar
    this.ruleIds[1] = 12; // attribute
    this.ruleIds[2] = 10; // attributeGroup
    this.ruleIds[3] = 13; // attributeName
    this.ruleIds[4] = 11; // attributeSet
    this.ruleIds[5] = 14; // attributeValue
    this.ruleIds[6] = 27; // BS
    this.ruleIds[7] = 7; // conceptId
    this.ruleIds[8] = 6; // conceptReference
    this.ruleIds[9] = 24; // CR
    this.ruleIds[10] = 19; // decimalValue
    this.ruleIds[11] = 2; // definitionStatus
    this.ruleIds[12] = 28; // digit
    this.ruleIds[13] = 30; // digitNonZero
    this.ruleIds[14] = 3; // equivalentTo
    this.ruleIds[15] = 33; // escapedChar
    this.ruleIds[16] = 0; // expression
    this.ruleIds[17] = 15; // expressionValue
    this.ruleIds[18] = 5; // focusConcept
    this.ruleIds[19] = 23; // HTAB
    this.ruleIds[20] = 18; // integerValue
    this.ruleIds[21] = 25; // LF
    this.ruleIds[22] = 31; // nonwsNonPipe
    this.ruleIds[23] = 17; // numericValue
    this.ruleIds[24] = 26; // QM
    this.ruleIds[25] = 9; // refinement
    this.ruleIds[26] = 20; // sctId
    this.ruleIds[27] = 22; // SP
    this.ruleIds[28] = 16; // stringValue
    this.ruleIds[29] = 1; // subExpression
    this.ruleIds[30] = 4; // subtypeOf
    this.ruleIds[31] = 8; // term
    this.ruleIds[32] = 34; // UTF8-2
    this.ruleIds[33] = 35; // UTF8-3
    this.ruleIds[34] = 36; // UTF8-4
    this.ruleIds[35] = 37; // UTF8-tail
    this.ruleIds[36] = 21; // ws
    this.ruleIds[37] = 29; // zero

    // rules
    this.rules = [];
    this.rules[0] = [];
    this.rules[0].rule = 'expression';
    this.rules[0].lower = 'expression';
    this.rules[0].syntax = null;
    this.rules[0].semantic = null;
    this.rules[0].opcodeIndex = 0;

    this.rules[1] = [];
    this.rules[1].rule = 'subExpression';
    this.rules[1].lower = 'subexpression';
    this.rules[1].syntax = null;
    this.rules[1].semantic = null;
    this.rules[1].opcodeIndex = 8;

    this.rules[2] = [];
    this.rules[2].rule = 'definitionStatus';
    this.rules[2].lower = 'definitionstatus';
    this.rules[2].syntax = null;
    this.rules[2].semantic = null;
    this.rules[2].opcodeIndex = 16;

    this.rules[3] = [];
    this.rules[3].rule = 'equivalentTo';
    this.rules[3].lower = 'equivalentto';
    this.rules[3].syntax = null;
    this.rules[3].semantic = null;
    this.rules[3].opcodeIndex = 19;

    this.rules[4] = [];
    this.rules[4].rule = 'subtypeOf';
    this.rules[4].lower = 'subtypeof';
    this.rules[4].syntax = null;
    this.rules[4].semantic = null;
    this.rules[4].opcodeIndex = 20;

    this.rules[5] = [];
    this.rules[5].rule = 'focusConcept';
    this.rules[5].lower = 'focusconcept';
    this.rules[5].syntax = null;
    this.rules[5].semantic = null;
    this.rules[5].opcodeIndex = 21;

    this.rules[6] = [];
    this.rules[6].rule = 'conceptReference';
    this.rules[6].lower = 'conceptreference';
    this.rules[6].syntax = null;
    this.rules[6].semantic = null;
    this.rules[6].opcodeIndex = 29;

    this.rules[7] = [];
    this.rules[7].rule = 'conceptId';
    this.rules[7].lower = 'conceptid';
    this.rules[7].syntax = null;
    this.rules[7].semantic = null;
    this.rules[7].opcodeIndex = 39;

    this.rules[8] = [];
    this.rules[8].rule = 'term';
    this.rules[8].lower = 'term';
    this.rules[8].syntax = null;
    this.rules[8].semantic = null;
    this.rules[8].opcodeIndex = 40;

    this.rules[9] = [];
    this.rules[9].rule = 'refinement';
    this.rules[9].lower = 'refinement';
    this.rules[9].syntax = null;
    this.rules[9].semantic = null;
    this.rules[9].opcodeIndex = 47;

    this.rules[10] = [];
    this.rules[10].rule = 'attributeGroup';
    this.rules[10].lower = 'attributegroup';
    this.rules[10].syntax = null;
    this.rules[10].semantic = null;
    this.rules[10].opcodeIndex = 59;

    this.rules[11] = [];
    this.rules[11].rule = 'attributeSet';
    this.rules[11].lower = 'attributeset';
    this.rules[11].syntax = null;
    this.rules[11].semantic = null;
    this.rules[11].opcodeIndex = 65;

    this.rules[12] = [];
    this.rules[12].rule = 'attribute';
    this.rules[12].lower = 'attribute';
    this.rules[12].syntax = null;
    this.rules[12].semantic = null;
    this.rules[12].opcodeIndex = 73;

    this.rules[13] = [];
    this.rules[13].rule = 'attributeName';
    this.rules[13].lower = 'attributename';
    this.rules[13].syntax = null;
    this.rules[13].semantic = null;
    this.rules[13].opcodeIndex = 79;

    this.rules[14] = [];
    this.rules[14].rule = 'attributeValue';
    this.rules[14].lower = 'attributevalue';
    this.rules[14].syntax = null;
    this.rules[14].semantic = null;
    this.rules[14].opcodeIndex = 80;

    this.rules[15] = [];
    this.rules[15].rule = 'expressionValue';
    this.rules[15].lower = 'expressionvalue';
    this.rules[15].syntax = null;
    this.rules[15].semantic = null;
    this.rules[15].opcodeIndex = 89;

    this.rules[16] = [];
    this.rules[16].rule = 'stringValue';
    this.rules[16].lower = 'stringvalue';
    this.rules[16].syntax = null;
    this.rules[16].semantic = null;
    this.rules[16].opcodeIndex = 97;

    this.rules[17] = [];
    this.rules[17].rule = 'numericValue';
    this.rules[17].lower = 'numericvalue';
    this.rules[17].syntax = null;
    this.rules[17].semantic = null;
    this.rules[17].opcodeIndex = 101;

    this.rules[18] = [];
    this.rules[18].rule = 'integerValue';
    this.rules[18].lower = 'integervalue';
    this.rules[18].syntax = null;
    this.rules[18].semantic = null;
    this.rules[18].opcodeIndex = 104;

    this.rules[19] = [];
    this.rules[19].rule = 'decimalValue';
    this.rules[19].lower = 'decimalvalue';
    this.rules[19].syntax = null;
    this.rules[19].semantic = null;
    this.rules[19].opcodeIndex = 114;

    this.rules[20] = [];
    this.rules[20].rule = 'sctId';
    this.rules[20].lower = 'sctid';
    this.rules[20].syntax = null;
    this.rules[20].semantic = null;
    this.rules[20].opcodeIndex = 119;

    this.rules[21] = [];
    this.rules[21].rule = 'ws';
    this.rules[21].lower = 'ws';
    this.rules[21].syntax = null;
    this.rules[21].semantic = null;
    this.rules[21].opcodeIndex = 123;

    this.rules[22] = [];
    this.rules[22].rule = 'SP';
    this.rules[22].lower = 'sp';
    this.rules[22].syntax = null;
    this.rules[22].semantic = null;
    this.rules[22].opcodeIndex = 129;

    this.rules[23] = [];
    this.rules[23].rule = 'HTAB';
    this.rules[23].lower = 'htab';
    this.rules[23].syntax = null;
    this.rules[23].semantic = null;
    this.rules[23].opcodeIndex = 130;

    this.rules[24] = [];
    this.rules[24].rule = 'CR';
    this.rules[24].lower = 'cr';
    this.rules[24].syntax = null;
    this.rules[24].semantic = null;
    this.rules[24].opcodeIndex = 131;

    this.rules[25] = [];
    this.rules[25].rule = 'LF';
    this.rules[25].lower = 'lf';
    this.rules[25].syntax = null;
    this.rules[25].semantic = null;
    this.rules[25].opcodeIndex = 132;

    this.rules[26] = [];
    this.rules[26].rule = 'QM';
    this.rules[26].lower = 'qm';
    this.rules[26].syntax = null;
    this.rules[26].semantic = null;
    this.rules[26].opcodeIndex = 133;

    this.rules[27] = [];
    this.rules[27].rule = 'BS';
    this.rules[27].lower = 'bs';
    this.rules[27].syntax = null;
    this.rules[27].semantic = null;
    this.rules[27].opcodeIndex = 134;

    this.rules[28] = [];
    this.rules[28].rule = 'digit';
    this.rules[28].lower = 'digit';
    this.rules[28].syntax = null;
    this.rules[28].semantic = null;
    this.rules[28].opcodeIndex = 135;

    this.rules[29] = [];
    this.rules[29].rule = 'zero';
    this.rules[29].lower = 'zero';
    this.rules[29].syntax = null;
    this.rules[29].semantic = null;
    this.rules[29].opcodeIndex = 136;

    this.rules[30] = [];
    this.rules[30].rule = 'digitNonZero';
    this.rules[30].lower = 'digitnonzero';
    this.rules[30].syntax = null;
    this.rules[30].semantic = null;
    this.rules[30].opcodeIndex = 137;

    this.rules[31] = [];
    this.rules[31].rule = 'nonwsNonPipe';
    this.rules[31].lower = 'nonwsnonpipe';
    this.rules[31].syntax = null;
    this.rules[31].semantic = null;
    this.rules[31].opcodeIndex = 138;

    this.rules[32] = [];
    this.rules[32].rule = 'anyNonEscapedChar';
    this.rules[32].lower = 'anynonescapedchar';
    this.rules[32].syntax = null;
    this.rules[32].semantic = null;
    this.rules[32].opcodeIndex = 144;

    this.rules[33] = [];
    this.rules[33].rule = 'escapedChar';
    this.rules[33].lower = 'escapedchar';
    this.rules[33].syntax = null;
    this.rules[33].semantic = null;
    this.rules[33].opcodeIndex = 154;

    this.rules[34] = [];
    this.rules[34].rule = 'UTF8-2';
    this.rules[34].lower = 'utf8-2';
    this.rules[34].syntax = null;
    this.rules[34].semantic = null;
    this.rules[34].opcodeIndex = 161;

    this.rules[35] = [];
    this.rules[35].rule = 'UTF8-3';
    this.rules[35].lower = 'utf8-3';
    this.rules[35].syntax = null;
    this.rules[35].semantic = null;
    this.rules[35].opcodeIndex = 164;

    this.rules[36] = [];
    this.rules[36].rule = 'UTF8-4';
    this.rules[36].lower = 'utf8-4';
    this.rules[36].syntax = null;
    this.rules[36].semantic = null;
    this.rules[36].opcodeIndex = 181;

    this.rules[37] = [];
    this.rules[37].rule = 'UTF8-tail';
    this.rules[37].lower = 'utf8-tail';
    this.rules[37].syntax = null;
    this.rules[37].semantic = null;
    this.rules[37].opcodeIndex = 196;

    // opcodes
    this.opcodes = [];
    this.opcodes[0] = [];
    this.opcodes[0].opNext = 8;
    this.opcodes[0].type = CAT;

    this.opcodes[1] = [];
    this.opcodes[1].opNext = 2;
    this.opcodes[1].type = RNM;
    this.opcodes[1].ruleIndex = 21;

    this.opcodes[2] = [];
    this.opcodes[2].opNext = 6;
    this.opcodes[2].type = REP;
    this.opcodes[2].min = 0;
    this.opcodes[2].max = 1;

    this.opcodes[3] = [];
    this.opcodes[3].opNext = 6;
    this.opcodes[3].type = CAT;

    this.opcodes[4] = [];
    this.opcodes[4].opNext = 5;
    this.opcodes[4].type = RNM;
    this.opcodes[4].ruleIndex = 2;

    this.opcodes[5] = [];
    this.opcodes[5].opNext = 6;
    this.opcodes[5].type = RNM;
    this.opcodes[5].ruleIndex = 21;

    this.opcodes[6] = [];
    this.opcodes[6].opNext = 7;
    this.opcodes[6].type = RNM;
    this.opcodes[6].ruleIndex = 1;

    this.opcodes[7] = [];
    this.opcodes[7].opNext = 8;
    this.opcodes[7].type = RNM;
    this.opcodes[7].ruleIndex = 21;

    this.opcodes[8] = [];
    this.opcodes[8].opNext = 16;
    this.opcodes[8].type = CAT;

    this.opcodes[9] = [];
    this.opcodes[9].opNext = 10;
    this.opcodes[9].type = RNM;
    this.opcodes[9].ruleIndex = 5;

    this.opcodes[10] = [];
    this.opcodes[10].opNext = 16;
    this.opcodes[10].type = REP;
    this.opcodes[10].min = 0;
    this.opcodes[10].max = 1;

    this.opcodes[11] = [];
    this.opcodes[11].opNext = 16;
    this.opcodes[11].type = CAT;

    this.opcodes[12] = [];
    this.opcodes[12].opNext = 13;
    this.opcodes[12].type = RNM;
    this.opcodes[12].ruleIndex = 21;

    this.opcodes[13] = [];
    this.opcodes[13].opNext = 14;
    this.opcodes[13].type = TLS;
    this.opcodes[13].length = 1;
    this.opcodes[13].stringIndex = 0;

    this.opcodes[14] = [];
    this.opcodes[14].opNext = 15;
    this.opcodes[14].type = RNM;
    this.opcodes[14].ruleIndex = 21;

    this.opcodes[15] = [];
    this.opcodes[15].opNext = 16;
    this.opcodes[15].type = RNM;
    this.opcodes[15].ruleIndex = 9;

    this.opcodes[16] = [];
    this.opcodes[16].opNext = 19;
    this.opcodes[16].type = ALT;

    this.opcodes[17] = [];
    this.opcodes[17].opNext = 18;
    this.opcodes[17].type = RNM;
    this.opcodes[17].ruleIndex = 3;

    this.opcodes[18] = [];
    this.opcodes[18].opNext = 19;
    this.opcodes[18].type = RNM;
    this.opcodes[18].ruleIndex = 4;

    this.opcodes[19] = [];
    this.opcodes[19].opNext = 20;
    this.opcodes[19].type = TLS;
    this.opcodes[19].length = 3;
    this.opcodes[19].stringIndex = 1;

    this.opcodes[20] = [];
    this.opcodes[20].opNext = 21;
    this.opcodes[20].type = TLS;
    this.opcodes[20].length = 3;
    this.opcodes[20].stringIndex = 4;

    this.opcodes[21] = [];
    this.opcodes[21].opNext = 29;
    this.opcodes[21].type = CAT;

    this.opcodes[22] = [];
    this.opcodes[22].opNext = 23;
    this.opcodes[22].type = RNM;
    this.opcodes[22].ruleIndex = 6;

    this.opcodes[23] = [];
    this.opcodes[23].opNext = 29;
    this.opcodes[23].type = REP;
    this.opcodes[23].min = 0;
    this.opcodes[23].max = Infinity;

    this.opcodes[24] = [];
    this.opcodes[24].opNext = 29;
    this.opcodes[24].type = CAT;

    this.opcodes[25] = [];
    this.opcodes[25].opNext = 26;
    this.opcodes[25].type = RNM;
    this.opcodes[25].ruleIndex = 21;

    this.opcodes[26] = [];
    this.opcodes[26].opNext = 27;
    this.opcodes[26].type = TLS;
    this.opcodes[26].length = 1;
    this.opcodes[26].stringIndex = 7;

    this.opcodes[27] = [];
    this.opcodes[27].opNext = 28;
    this.opcodes[27].type = RNM;
    this.opcodes[27].ruleIndex = 21;

    this.opcodes[28] = [];
    this.opcodes[28].opNext = 29;
    this.opcodes[28].type = RNM;
    this.opcodes[28].ruleIndex = 6;

    this.opcodes[29] = [];
    this.opcodes[29].opNext = 39;
    this.opcodes[29].type = CAT;

    this.opcodes[30] = [];
    this.opcodes[30].opNext = 31;
    this.opcodes[30].type = RNM;
    this.opcodes[30].ruleIndex = 7;

    this.opcodes[31] = [];
    this.opcodes[31].opNext = 39;
    this.opcodes[31].type = REP;
    this.opcodes[31].min = 0;
    this.opcodes[31].max = 1;

    this.opcodes[32] = [];
    this.opcodes[32].opNext = 39;
    this.opcodes[32].type = CAT;

    this.opcodes[33] = [];
    this.opcodes[33].opNext = 34;
    this.opcodes[33].type = RNM;
    this.opcodes[33].ruleIndex = 21;

    this.opcodes[34] = [];
    this.opcodes[34].opNext = 35;
    this.opcodes[34].type = TLS;
    this.opcodes[34].length = 1;
    this.opcodes[34].stringIndex = 8;

    this.opcodes[35] = [];
    this.opcodes[35].opNext = 36;
    this.opcodes[35].type = RNM;
    this.opcodes[35].ruleIndex = 21;

    this.opcodes[36] = [];
    this.opcodes[36].opNext = 37;
    this.opcodes[36].type = RNM;
    this.opcodes[36].ruleIndex = 8;

    this.opcodes[37] = [];
    this.opcodes[37].opNext = 38;
    this.opcodes[37].type = RNM;
    this.opcodes[37].ruleIndex = 21;

    this.opcodes[38] = [];
    this.opcodes[38].opNext = 39;
    this.opcodes[38].type = TLS;
    this.opcodes[38].length = 1;
    this.opcodes[38].stringIndex = 9;

    this.opcodes[39] = [];
    this.opcodes[39].opNext = 40;
    this.opcodes[39].type = RNM;
    this.opcodes[39].ruleIndex = 20;

    this.opcodes[40] = [];
    this.opcodes[40].opNext = 47;
    this.opcodes[40].type = CAT;

    this.opcodes[41] = [];
    this.opcodes[41].opNext = 42;
    this.opcodes[41].type = RNM;
    this.opcodes[41].ruleIndex = 31;

    this.opcodes[42] = [];
    this.opcodes[42].opNext = 47;
    this.opcodes[42].type = REP;
    this.opcodes[42].min = 0;
    this.opcodes[42].max = Infinity;

    this.opcodes[43] = [];
    this.opcodes[43].opNext = 47;
    this.opcodes[43].type = CAT;

    this.opcodes[44] = [];
    this.opcodes[44].opNext = 46;
    this.opcodes[44].type = REP;
    this.opcodes[44].min = 0;
    this.opcodes[44].max = Infinity;

    this.opcodes[45] = [];
    this.opcodes[45].opNext = 46;
    this.opcodes[45].type = RNM;
    this.opcodes[45].ruleIndex = 22;

    this.opcodes[46] = [];
    this.opcodes[46].opNext = 47;
    this.opcodes[46].type = RNM;
    this.opcodes[46].ruleIndex = 31;

    this.opcodes[47] = [];
    this.opcodes[47].opNext = 59;
    this.opcodes[47].type = CAT;

    this.opcodes[48] = [];
    this.opcodes[48].opNext = 51;
    this.opcodes[48].type = ALT;

    this.opcodes[49] = [];
    this.opcodes[49].opNext = 50;
    this.opcodes[49].type = RNM;
    this.opcodes[49].ruleIndex = 11;

    this.opcodes[50] = [];
    this.opcodes[50].opNext = 51;
    this.opcodes[50].type = RNM;
    this.opcodes[50].ruleIndex = 10;

    this.opcodes[51] = [];
    this.opcodes[51].opNext = 59;
    this.opcodes[51].type = REP;
    this.opcodes[51].min = 0;
    this.opcodes[51].max = Infinity;

    this.opcodes[52] = [];
    this.opcodes[52].opNext = 59;
    this.opcodes[52].type = CAT;

    this.opcodes[53] = [];
    this.opcodes[53].opNext = 54;
    this.opcodes[53].type = RNM;
    this.opcodes[53].ruleIndex = 21;

    this.opcodes[54] = [];
    this.opcodes[54].opNext = 58;
    this.opcodes[54].type = REP;
    this.opcodes[54].min = 0;
    this.opcodes[54].max = 1;

    this.opcodes[55] = [];
    this.opcodes[55].opNext = 58;
    this.opcodes[55].type = CAT;

    this.opcodes[56] = [];
    this.opcodes[56].opNext = 57;
    this.opcodes[56].type = TLS;
    this.opcodes[56].length = 1;
    this.opcodes[56].stringIndex = 10;

    this.opcodes[57] = [];
    this.opcodes[57].opNext = 58;
    this.opcodes[57].type = RNM;
    this.opcodes[57].ruleIndex = 21;

    this.opcodes[58] = [];
    this.opcodes[58].opNext = 59;
    this.opcodes[58].type = RNM;
    this.opcodes[58].ruleIndex = 10;

    this.opcodes[59] = [];
    this.opcodes[59].opNext = 65;
    this.opcodes[59].type = CAT;

    this.opcodes[60] = [];
    this.opcodes[60].opNext = 61;
    this.opcodes[60].type = TLS;
    this.opcodes[60].length = 1;
    this.opcodes[60].stringIndex = 11;

    this.opcodes[61] = [];
    this.opcodes[61].opNext = 62;
    this.opcodes[61].type = RNM;
    this.opcodes[61].ruleIndex = 21;

    this.opcodes[62] = [];
    this.opcodes[62].opNext = 63;
    this.opcodes[62].type = RNM;
    this.opcodes[62].ruleIndex = 11;

    this.opcodes[63] = [];
    this.opcodes[63].opNext = 64;
    this.opcodes[63].type = RNM;
    this.opcodes[63].ruleIndex = 21;

    this.opcodes[64] = [];
    this.opcodes[64].opNext = 65;
    this.opcodes[64].type = TLS;
    this.opcodes[64].length = 1;
    this.opcodes[64].stringIndex = 12;

    this.opcodes[65] = [];
    this.opcodes[65].opNext = 73;
    this.opcodes[65].type = CAT;

    this.opcodes[66] = [];
    this.opcodes[66].opNext = 67;
    this.opcodes[66].type = RNM;
    this.opcodes[66].ruleIndex = 12;

    this.opcodes[67] = [];
    this.opcodes[67].opNext = 73;
    this.opcodes[67].type = REP;
    this.opcodes[67].min = 0;
    this.opcodes[67].max = Infinity;

    this.opcodes[68] = [];
    this.opcodes[68].opNext = 73;
    this.opcodes[68].type = CAT;

    this.opcodes[69] = [];
    this.opcodes[69].opNext = 70;
    this.opcodes[69].type = RNM;
    this.opcodes[69].ruleIndex = 21;

    this.opcodes[70] = [];
    this.opcodes[70].opNext = 71;
    this.opcodes[70].type = TLS;
    this.opcodes[70].length = 1;
    this.opcodes[70].stringIndex = 13;

    this.opcodes[71] = [];
    this.opcodes[71].opNext = 72;
    this.opcodes[71].type = RNM;
    this.opcodes[71].ruleIndex = 21;

    this.opcodes[72] = [];
    this.opcodes[72].opNext = 73;
    this.opcodes[72].type = RNM;
    this.opcodes[72].ruleIndex = 12;

    this.opcodes[73] = [];
    this.opcodes[73].opNext = 79;
    this.opcodes[73].type = CAT;

    this.opcodes[74] = [];
    this.opcodes[74].opNext = 75;
    this.opcodes[74].type = RNM;
    this.opcodes[74].ruleIndex = 13;

    this.opcodes[75] = [];
    this.opcodes[75].opNext = 76;
    this.opcodes[75].type = RNM;
    this.opcodes[75].ruleIndex = 21;

    this.opcodes[76] = [];
    this.opcodes[76].opNext = 77;
    this.opcodes[76].type = TLS;
    this.opcodes[76].length = 1;
    this.opcodes[76].stringIndex = 14;

    this.opcodes[77] = [];
    this.opcodes[77].opNext = 78;
    this.opcodes[77].type = RNM;
    this.opcodes[77].ruleIndex = 21;

    this.opcodes[78] = [];
    this.opcodes[78].opNext = 79;
    this.opcodes[78].type = RNM;
    this.opcodes[78].ruleIndex = 14;

    this.opcodes[79] = [];
    this.opcodes[79].opNext = 80;
    this.opcodes[79].type = RNM;
    this.opcodes[79].ruleIndex = 6;

    this.opcodes[80] = [];
    this.opcodes[80].opNext = 89;
    this.opcodes[80].type = ALT;

    this.opcodes[81] = [];
    this.opcodes[81].opNext = 82;
    this.opcodes[81].type = RNM;
    this.opcodes[81].ruleIndex = 15;

    this.opcodes[82] = [];
    this.opcodes[82].opNext = 86;
    this.opcodes[82].type = CAT;

    this.opcodes[83] = [];
    this.opcodes[83].opNext = 84;
    this.opcodes[83].type = RNM;
    this.opcodes[83].ruleIndex = 26;

    this.opcodes[84] = [];
    this.opcodes[84].opNext = 85;
    this.opcodes[84].type = RNM;
    this.opcodes[84].ruleIndex = 16;

    this.opcodes[85] = [];
    this.opcodes[85].opNext = 86;
    this.opcodes[85].type = RNM;
    this.opcodes[85].ruleIndex = 26;

    this.opcodes[86] = [];
    this.opcodes[86].opNext = 89;
    this.opcodes[86].type = CAT;

    this.opcodes[87] = [];
    this.opcodes[87].opNext = 88;
    this.opcodes[87].type = TLS;
    this.opcodes[87].length = 1;
    this.opcodes[87].stringIndex = 15;

    this.opcodes[88] = [];
    this.opcodes[88].opNext = 89;
    this.opcodes[88].type = RNM;
    this.opcodes[88].ruleIndex = 17;

    this.opcodes[89] = [];
    this.opcodes[89].opNext = 97;
    this.opcodes[89].type = ALT;

    this.opcodes[90] = [];
    this.opcodes[90].opNext = 91;
    this.opcodes[90].type = RNM;
    this.opcodes[90].ruleIndex = 6;

    this.opcodes[91] = [];
    this.opcodes[91].opNext = 97;
    this.opcodes[91].type = CAT;

    this.opcodes[92] = [];
    this.opcodes[92].opNext = 93;
    this.opcodes[92].type = TLS;
    this.opcodes[92].length = 1;
    this.opcodes[92].stringIndex = 16;

    this.opcodes[93] = [];
    this.opcodes[93].opNext = 94;
    this.opcodes[93].type = RNM;
    this.opcodes[93].ruleIndex = 21;

    this.opcodes[94] = [];
    this.opcodes[94].opNext = 95;
    this.opcodes[94].type = RNM;
    this.opcodes[94].ruleIndex = 1;

    this.opcodes[95] = [];
    this.opcodes[95].opNext = 96;
    this.opcodes[95].type = RNM;
    this.opcodes[95].ruleIndex = 21;

    this.opcodes[96] = [];
    this.opcodes[96].opNext = 97;
    this.opcodes[96].type = TLS;
    this.opcodes[96].length = 1;
    this.opcodes[96].stringIndex = 17;

    this.opcodes[97] = [];
    this.opcodes[97].opNext = 101;
    this.opcodes[97].type = REP;
    this.opcodes[97].min = 1;
    this.opcodes[97].max = Infinity;

    this.opcodes[98] = [];
    this.opcodes[98].opNext = 101;
    this.opcodes[98].type = ALT;

    this.opcodes[99] = [];
    this.opcodes[99].opNext = 100;
    this.opcodes[99].type = RNM;
    this.opcodes[99].ruleIndex = 32;

    this.opcodes[100] = [];
    this.opcodes[100].opNext = 101;
    this.opcodes[100].type = RNM;
    this.opcodes[100].ruleIndex = 33;

    this.opcodes[101] = [];
    this.opcodes[101].opNext = 104;
    this.opcodes[101].type = ALT;

    this.opcodes[102] = [];
    this.opcodes[102].opNext = 103;
    this.opcodes[102].type = RNM;
    this.opcodes[102].ruleIndex = 19;

    this.opcodes[103] = [];
    this.opcodes[103].opNext = 104;
    this.opcodes[103].type = RNM;
    this.opcodes[103].ruleIndex = 18;

    this.opcodes[104] = [];
    this.opcodes[104].opNext = 114;
    this.opcodes[104].type = ALT;

    this.opcodes[105] = [];
    this.opcodes[105].opNext = 113;
    this.opcodes[105].type = CAT;

    this.opcodes[106] = [];
    this.opcodes[106].opNext = 110;
    this.opcodes[106].type = REP;
    this.opcodes[106].min = 0;
    this.opcodes[106].max = 1;

    this.opcodes[107] = [];
    this.opcodes[107].opNext = 110;
    this.opcodes[107].type = ALT;

    this.opcodes[108] = [];
    this.opcodes[108].opNext = 109;
    this.opcodes[108].type = TLS;
    this.opcodes[108].length = 1;
    this.opcodes[108].stringIndex = 18;

    this.opcodes[109] = [];
    this.opcodes[109].opNext = 110;
    this.opcodes[109].type = TLS;
    this.opcodes[109].length = 1;
    this.opcodes[109].stringIndex = 19;

    this.opcodes[110] = [];
    this.opcodes[110].opNext = 111;
    this.opcodes[110].type = RNM;
    this.opcodes[110].ruleIndex = 30;

    this.opcodes[111] = [];
    this.opcodes[111].opNext = 113;
    this.opcodes[111].type = REP;
    this.opcodes[111].min = 0;
    this.opcodes[111].max = Infinity;

    this.opcodes[112] = [];
    this.opcodes[112].opNext = 113;
    this.opcodes[112].type = RNM;
    this.opcodes[112].ruleIndex = 28;

    this.opcodes[113] = [];
    this.opcodes[113].opNext = 114;
    this.opcodes[113].type = RNM;
    this.opcodes[113].ruleIndex = 29;

    this.opcodes[114] = [];
    this.opcodes[114].opNext = 119;
    this.opcodes[114].type = CAT;

    this.opcodes[115] = [];
    this.opcodes[115].opNext = 116;
    this.opcodes[115].type = RNM;
    this.opcodes[115].ruleIndex = 18;

    this.opcodes[116] = [];
    this.opcodes[116].opNext = 117;
    this.opcodes[116].type = TLS;
    this.opcodes[116].length = 1;
    this.opcodes[116].stringIndex = 20;

    this.opcodes[117] = [];
    this.opcodes[117].opNext = 119;
    this.opcodes[117].type = REP;
    this.opcodes[117].min = 1;
    this.opcodes[117].max = Infinity;

    this.opcodes[118] = [];
    this.opcodes[118].opNext = 119;
    this.opcodes[118].type = RNM;
    this.opcodes[118].ruleIndex = 28;

    this.opcodes[119] = [];
    this.opcodes[119].opNext = 123;
    this.opcodes[119].type = CAT;

    this.opcodes[120] = [];
    this.opcodes[120].opNext = 121;
    this.opcodes[120].type = RNM;
    this.opcodes[120].ruleIndex = 30;

    this.opcodes[121] = [];
    this.opcodes[121].opNext = 123;
    this.opcodes[121].type = REP;
    this.opcodes[121].min = 5;
    this.opcodes[121].max = 17;

    this.opcodes[122] = [];
    this.opcodes[122].opNext = 123;
    this.opcodes[122].type = RNM;
    this.opcodes[122].ruleIndex = 28;

    this.opcodes[123] = [];
    this.opcodes[123].opNext = 129;
    this.opcodes[123].type = REP;
    this.opcodes[123].min = 0;
    this.opcodes[123].max = Infinity;

    this.opcodes[124] = [];
    this.opcodes[124].opNext = 129;
    this.opcodes[124].type = ALT;

    this.opcodes[125] = [];
    this.opcodes[125].opNext = 126;
    this.opcodes[125].type = RNM;
    this.opcodes[125].ruleIndex = 22;

    this.opcodes[126] = [];
    this.opcodes[126].opNext = 127;
    this.opcodes[126].type = RNM;
    this.opcodes[126].ruleIndex = 23;

    this.opcodes[127] = [];
    this.opcodes[127].opNext = 128;
    this.opcodes[127].type = RNM;
    this.opcodes[127].ruleIndex = 24;

    this.opcodes[128] = [];
    this.opcodes[128].opNext = 129;
    this.opcodes[128].type = RNM;
    this.opcodes[128].ruleIndex = 25;

    this.opcodes[129] = [];
    this.opcodes[129].opNext = 130;
    this.opcodes[129].type = TRG;
    this.opcodes[129].min = 32;
    this.opcodes[129].max = 32;

    this.opcodes[130] = [];
    this.opcodes[130].opNext = 131;
    this.opcodes[130].type = TRG;
    this.opcodes[130].min = 9;
    this.opcodes[130].max = 9;

    this.opcodes[131] = [];
    this.opcodes[131].opNext = 132;
    this.opcodes[131].type = TRG;
    this.opcodes[131].min = 13;
    this.opcodes[131].max = 13;

    this.opcodes[132] = [];
    this.opcodes[132].opNext = 133;
    this.opcodes[132].type = TRG;
    this.opcodes[132].min = 10;
    this.opcodes[132].max = 10;

    this.opcodes[133] = [];
    this.opcodes[133].opNext = 134;
    this.opcodes[133].type = TRG;
    this.opcodes[133].min = 34;
    this.opcodes[133].max = 34;

    this.opcodes[134] = [];
    this.opcodes[134].opNext = 135;
    this.opcodes[134].type = TRG;
    this.opcodes[134].min = 92;
    this.opcodes[134].max = 92;

    this.opcodes[135] = [];
    this.opcodes[135].opNext = 136;
    this.opcodes[135].type = TRG;
    this.opcodes[135].min = 48;
    this.opcodes[135].max = 57;

    this.opcodes[136] = [];
    this.opcodes[136].opNext = 137;
    this.opcodes[136].type = TRG;
    this.opcodes[136].min = 48;
    this.opcodes[136].max = 48;

    this.opcodes[137] = [];
    this.opcodes[137].opNext = 138;
    this.opcodes[137].type = TRG;
    this.opcodes[137].min = 49;
    this.opcodes[137].max = 57;

    this.opcodes[138] = [];
    this.opcodes[138].opNext = 144;
    this.opcodes[138].type = ALT;

    this.opcodes[139] = [];
    this.opcodes[139].opNext = 140;
    this.opcodes[139].type = TRG;
    this.opcodes[139].min = 33;
    this.opcodes[139].max = 123;

    this.opcodes[140] = [];
    this.opcodes[140].opNext = 141;
    this.opcodes[140].type = TRG;
    this.opcodes[140].min = 125;
    this.opcodes[140].max = 126;

    this.opcodes[141] = [];
    this.opcodes[141].opNext = 142;
    this.opcodes[141].type = RNM;
    this.opcodes[141].ruleIndex = 34;

    this.opcodes[142] = [];
    this.opcodes[142].opNext = 143;
    this.opcodes[142].type = RNM;
    this.opcodes[142].ruleIndex = 35;

    this.opcodes[143] = [];
    this.opcodes[143].opNext = 144;
    this.opcodes[143].type = RNM;
    this.opcodes[143].ruleIndex = 36;

    this.opcodes[144] = [];
    this.opcodes[144].opNext = 154;
    this.opcodes[144].type = ALT;

    this.opcodes[145] = [];
    this.opcodes[145].opNext = 146;
    this.opcodes[145].type = RNM;
    this.opcodes[145].ruleIndex = 23;

    this.opcodes[146] = [];
    this.opcodes[146].opNext = 147;
    this.opcodes[146].type = RNM;
    this.opcodes[146].ruleIndex = 24;

    this.opcodes[147] = [];
    this.opcodes[147].opNext = 148;
    this.opcodes[147].type = RNM;
    this.opcodes[147].ruleIndex = 25;

    this.opcodes[148] = [];
    this.opcodes[148].opNext = 149;
    this.opcodes[148].type = TRG;
    this.opcodes[148].min = 32;
    this.opcodes[148].max = 33;

    this.opcodes[149] = [];
    this.opcodes[149].opNext = 150;
    this.opcodes[149].type = TRG;
    this.opcodes[149].min = 35;
    this.opcodes[149].max = 91;

    this.opcodes[150] = [];
    this.opcodes[150].opNext = 151;
    this.opcodes[150].type = TRG;
    this.opcodes[150].min = 93;
    this.opcodes[150].max = 126;

    this.opcodes[151] = [];
    this.opcodes[151].opNext = 152;
    this.opcodes[151].type = RNM;
    this.opcodes[151].ruleIndex = 34;

    this.opcodes[152] = [];
    this.opcodes[152].opNext = 153;
    this.opcodes[152].type = RNM;
    this.opcodes[152].ruleIndex = 35;

    this.opcodes[153] = [];
    this.opcodes[153].opNext = 154;
    this.opcodes[153].type = RNM;
    this.opcodes[153].ruleIndex = 36;

    this.opcodes[154] = [];
    this.opcodes[154].opNext = 161;
    this.opcodes[154].type = ALT;

    this.opcodes[155] = [];
    this.opcodes[155].opNext = 158;
    this.opcodes[155].type = CAT;

    this.opcodes[156] = [];
    this.opcodes[156].opNext = 157;
    this.opcodes[156].type = RNM;
    this.opcodes[156].ruleIndex = 27;

    this.opcodes[157] = [];
    this.opcodes[157].opNext = 158;
    this.opcodes[157].type = RNM;
    this.opcodes[157].ruleIndex = 26;

    this.opcodes[158] = [];
    this.opcodes[158].opNext = 161;
    this.opcodes[158].type = CAT;

    this.opcodes[159] = [];
    this.opcodes[159].opNext = 160;
    this.opcodes[159].type = RNM;
    this.opcodes[159].ruleIndex = 27;

    this.opcodes[160] = [];
    this.opcodes[160].opNext = 161;
    this.opcodes[160].type = RNM;
    this.opcodes[160].ruleIndex = 27;

    this.opcodes[161] = [];
    this.opcodes[161].opNext = 164;
    this.opcodes[161].type = CAT;

    this.opcodes[162] = [];
    this.opcodes[162].opNext = 163;
    this.opcodes[162].type = TRG;
    this.opcodes[162].min = 194;
    this.opcodes[162].max = 223;

    this.opcodes[163] = [];
    this.opcodes[163].opNext = 164;
    this.opcodes[163].type = RNM;
    this.opcodes[163].ruleIndex = 37;

    this.opcodes[164] = [];
    this.opcodes[164].opNext = 181;
    this.opcodes[164].type = ALT;

    this.opcodes[165] = [];
    this.opcodes[165].opNext = 169;
    this.opcodes[165].type = CAT;

    this.opcodes[166] = [];
    this.opcodes[166].opNext = 167;
    this.opcodes[166].type = TRG;
    this.opcodes[166].min = 224;
    this.opcodes[166].max = 224;

    this.opcodes[167] = [];
    this.opcodes[167].opNext = 168;
    this.opcodes[167].type = TRG;
    this.opcodes[167].min = 160;
    this.opcodes[167].max = 191;

    this.opcodes[168] = [];
    this.opcodes[168].opNext = 169;
    this.opcodes[168].type = RNM;
    this.opcodes[168].ruleIndex = 37;

    this.opcodes[169] = [];
    this.opcodes[169].opNext = 173;
    this.opcodes[169].type = CAT;

    this.opcodes[170] = [];
    this.opcodes[170].opNext = 171;
    this.opcodes[170].type = TRG;
    this.opcodes[170].min = 225;
    this.opcodes[170].max = 236;

    this.opcodes[171] = [];
    this.opcodes[171].opNext = 173;
    this.opcodes[171].type = REP;
    this.opcodes[171].min = 2;
    this.opcodes[171].max = 2;

    this.opcodes[172] = [];
    this.opcodes[172].opNext = 173;
    this.opcodes[172].type = RNM;
    this.opcodes[172].ruleIndex = 37;

    this.opcodes[173] = [];
    this.opcodes[173].opNext = 177;
    this.opcodes[173].type = CAT;

    this.opcodes[174] = [];
    this.opcodes[174].opNext = 175;
    this.opcodes[174].type = TRG;
    this.opcodes[174].min = 237;
    this.opcodes[174].max = 237;

    this.opcodes[175] = [];
    this.opcodes[175].opNext = 176;
    this.opcodes[175].type = TRG;
    this.opcodes[175].min = 128;
    this.opcodes[175].max = 159;

    this.opcodes[176] = [];
    this.opcodes[176].opNext = 177;
    this.opcodes[176].type = RNM;
    this.opcodes[176].ruleIndex = 37;

    this.opcodes[177] = [];
    this.opcodes[177].opNext = 181;
    this.opcodes[177].type = CAT;

    this.opcodes[178] = [];
    this.opcodes[178].opNext = 179;
    this.opcodes[178].type = TRG;
    this.opcodes[178].min = 238;
    this.opcodes[178].max = 239;

    this.opcodes[179] = [];
    this.opcodes[179].opNext = 181;
    this.opcodes[179].type = REP;
    this.opcodes[179].min = 2;
    this.opcodes[179].max = 2;

    this.opcodes[180] = [];
    this.opcodes[180].opNext = 181;
    this.opcodes[180].type = RNM;
    this.opcodes[180].ruleIndex = 37;

    this.opcodes[181] = [];
    this.opcodes[181].opNext = 196;
    this.opcodes[181].type = ALT;

    this.opcodes[182] = [];
    this.opcodes[182].opNext = 187;
    this.opcodes[182].type = CAT;

    this.opcodes[183] = [];
    this.opcodes[183].opNext = 184;
    this.opcodes[183].type = TRG;
    this.opcodes[183].min = 240;
    this.opcodes[183].max = 240;

    this.opcodes[184] = [];
    this.opcodes[184].opNext = 185;
    this.opcodes[184].type = TRG;
    this.opcodes[184].min = 144;
    this.opcodes[184].max = 191;

    this.opcodes[185] = [];
    this.opcodes[185].opNext = 187;
    this.opcodes[185].type = REP;
    this.opcodes[185].min = 2;
    this.opcodes[185].max = 2;

    this.opcodes[186] = [];
    this.opcodes[186].opNext = 187;
    this.opcodes[186].type = RNM;
    this.opcodes[186].ruleIndex = 37;

    this.opcodes[187] = [];
    this.opcodes[187].opNext = 191;
    this.opcodes[187].type = CAT;

    this.opcodes[188] = [];
    this.opcodes[188].opNext = 189;
    this.opcodes[188].type = TRG;
    this.opcodes[188].min = 241;
    this.opcodes[188].max = 243;

    this.opcodes[189] = [];
    this.opcodes[189].opNext = 191;
    this.opcodes[189].type = REP;
    this.opcodes[189].min = 3;
    this.opcodes[189].max = 3;

    this.opcodes[190] = [];
    this.opcodes[190].opNext = 191;
    this.opcodes[190].type = RNM;
    this.opcodes[190].ruleIndex = 37;

    this.opcodes[191] = [];
    this.opcodes[191].opNext = 196;
    this.opcodes[191].type = CAT;

    this.opcodes[192] = [];
    this.opcodes[192].opNext = 193;
    this.opcodes[192].type = TRG;
    this.opcodes[192].min = 244;
    this.opcodes[192].max = 244;

    this.opcodes[193] = [];
    this.opcodes[193].opNext = 194;
    this.opcodes[193].type = TRG;
    this.opcodes[193].min = 128;
    this.opcodes[193].max = 143;

    this.opcodes[194] = [];
    this.opcodes[194].opNext = 196;
    this.opcodes[194].type = REP;
    this.opcodes[194].min = 2;
    this.opcodes[194].max = 2;

    this.opcodes[195] = [];
    this.opcodes[195].opNext = 196;
    this.opcodes[195].type = RNM;
    this.opcodes[195].ruleIndex = 37;

    this.opcodes[196] = [];
    this.opcodes[196].opNext = 197;
    this.opcodes[196].type = TRG;
    this.opcodes[196].min = 128;
    this.opcodes[196].max = 191;

}