/*
Generated by:
JavaScript APG, Version 1.0
an ABNF Parser Generator

Copyright (C) 2009 Lowell D. Thomas, all rights reserved

email: lowell@coasttocoastresearch.com
website: http://www.coasttocoastresearch.com

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see
<http://www.gnu.org/licenses/old-licenses/gpl-2.0.html>
or write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA.
*/
function ABNFOpcodes()
{
    // SUMMARY
    // string table length: 76
    //               rules: 75
    //             opcodes: 432

    // string table
    this.stringTable = [];
    this.stringTable[0] = 58;
    this.stringTable[1] = 40;
    this.stringTable[2] = 41;
    this.stringTable[3] = 46;
    this.stringTable[4] = 94;
    this.stringTable[5] = 124;
    this.stringTable[6] = 124;
    this.stringTable[7] = 42;
    this.stringTable[8] = 60;
    this.stringTable[9] = 60;
    this.stringTable[10] = 60;
    this.stringTable[11] = 60;
    this.stringTable[12] = 33;
    this.stringTable[13] = 62;
    this.stringTable[14] = 62;
    this.stringTable[15] = 62;
    this.stringTable[16] = 62;
    this.stringTable[17] = 33;
    this.stringTable[18] = 97;
    this.stringTable[19] = 65;
    this.stringTable[20] = 110;
    this.stringTable[21] = 78;
    this.stringTable[22] = 100;
    this.stringTable[23] = 68;
    this.stringTable[24] = 44;
    this.stringTable[25] = 111;
    this.stringTable[26] = 79;
    this.stringTable[27] = 114;
    this.stringTable[28] = 82;
    this.stringTable[29] = 109;
    this.stringTable[30] = 77;
    this.stringTable[31] = 105;
    this.stringTable[32] = 73;
    this.stringTable[33] = 110;
    this.stringTable[34] = 78;
    this.stringTable[35] = 117;
    this.stringTable[36] = 85;
    this.stringTable[37] = 115;
    this.stringTable[38] = 83;
    this.stringTable[39] = 40;
    this.stringTable[40] = 41;
    this.stringTable[41] = 40;
    this.stringTable[42] = 41;
    this.stringTable[43] = 91;
    this.stringTable[44] = 93;
    this.stringTable[45] = 123;
    this.stringTable[46] = 125;
    this.stringTable[47] = 91;
    this.stringTable[48] = 93;
    this.stringTable[49] = 35;
    this.stringTable[50] = 46;
    this.stringTable[51] = 46;
    this.stringTable[52] = 42;
    this.stringTable[53] = 82;
    this.stringTable[54] = 61;
    this.stringTable[55] = 33;
    this.stringTable[56] = 61;
    this.stringTable[57] = 61;
    this.stringTable[58] = 33;
    this.stringTable[59] = 61;
    this.stringTable[60] = 60;
    this.stringTable[61] = 61;
    this.stringTable[62] = 60;
    this.stringTable[63] = 62;
    this.stringTable[64] = 61;
    this.stringTable[65] = 62;
    this.stringTable[66] = 61;
    this.stringTable[67] = 33;
    this.stringTable[68] = 61;
    this.stringTable[69] = 45;
    this.stringTable[70] = 43;
    this.stringTable[71] = 46;
    this.stringTable[72] = 47;
    this.stringTable[73] = 42;
    this.stringTable[74] = 42;
    this.stringTable[75] = 47;

    // rule identifiers
    this.ruleIds = [];
    this.ruleIds.expressionconstraint = 0;
    this.ruleIds.refinedexpressionconstraint = 1;
    this.ruleIds.compoundexpressionconstraint = 2;
    this.ruleIds.conjunctionexpressionconstraint = 3;
    this.ruleIds.disjunctionexpressionconstraint = 4;
    this.ruleIds.exclusionexpressionconstraint = 5;
    this.ruleIds.dottedexpressionconstraint = 6;
    this.ruleIds.subexpressionconstraint = 7;
    this.ruleIds.simpleexpressionconstraint = 8;
    this.ruleIds.eclfocusconcept = 9;
    this.ruleIds.dot = 10;
    this.ruleIds.memberof = 11;
    this.ruleIds.conceptreference = 12;
    this.ruleIds.conceptid = 13;
    this.ruleIds.term = 14;
    this.ruleIds.wildcard = 15;
    this.ruleIds.constraintoperator = 16;
    this.ruleIds.descendantof = 17;
    this.ruleIds.descendantorselfof = 18;
    this.ruleIds.childof = 19;
    this.ruleIds.ancestorof = 20;
    this.ruleIds.ancestororselfof = 21;
    this.ruleIds.parentof = 22;
    this.ruleIds.conjunction = 23;
    this.ruleIds.disjunction = 24;
    this.ruleIds.exclusion = 25;
    this.ruleIds.eclrefinement = 26;
    this.ruleIds.conjunctionrefinementset = 27;
    this.ruleIds.disjunctionrefinementset = 28;
    this.ruleIds.subrefinement = 29;
    this.ruleIds.eclattributeset = 30;
    this.ruleIds.conjunctionattributeset = 31;
    this.ruleIds.disjunctionattributeset = 32;
    this.ruleIds.subattributeset = 33;
    this.ruleIds.eclattributegroup = 34;
    this.ruleIds.eclattribute = 35;
    this.ruleIds.cardinality = 36;
    this.ruleIds.minvalue = 37;
    this.ruleIds.to = 38;
    this.ruleIds.maxvalue = 39;
    this.ruleIds.many = 40;
    this.ruleIds.reverseflag = 41;
    this.ruleIds.attributeoperator = 42;
    this.ruleIds.eclattributename = 43;
    this.ruleIds.expressioncomparisonoperator = 44;
    this.ruleIds.numericcomparisonoperator = 45;
    this.ruleIds.stringcomparisonoperator = 46;
    this.ruleIds.numericvalue = 47;
    this.ruleIds.stringvalue = 48;
    this.ruleIds.integervalue = 49;
    this.ruleIds.decimalvalue = 50;
    this.ruleIds.nonnegativeintegervalue = 51;
    this.ruleIds.sctid = 52;
    this.ruleIds.ws = 53;
    this.ruleIds.mws = 54;
    this.ruleIds.comment = 55;
    this.ruleIds.nonstarchar = 56;
    this.ruleIds.starwithnonfslash = 57;
    this.ruleIds.nonfslash = 58;
    this.ruleIds.sp = 59;
    this.ruleIds.htab = 60;
    this.ruleIds.cr = 61;
    this.ruleIds.lf = 62;
    this.ruleIds.qm = 63;
    this.ruleIds.bs = 64;
    this.ruleIds.digit = 65;
    this.ruleIds.zero = 66;
    this.ruleIds.digitnonzero = 67;
    this.ruleIds.nonwsnonpipe = 68;
    this.ruleIds.anynonescapedchar = 69;
    this.ruleIds.escapedchar = 70;
    this.ruleIds['utf8-2'] = 71;
    this.ruleIds['utf8-3'] = 72;
    this.ruleIds['utf8-4'] = 73;
    this.ruleIds['utf8-tail'] = 74;

    // rule identifiers (alphabetical)
    this.ruleIds[0] = 20; // ancestorOf
    this.ruleIds[1] = 21; // ancestorOrSelfOf
    this.ruleIds[2] = 69; // anyNonEscapedChar
    this.ruleIds[3] = 42; // attributeOperator
    this.ruleIds[4] = 64; // BS
    this.ruleIds[5] = 36; // cardinality
    this.ruleIds[6] = 19; // childOf
    this.ruleIds[7] = 55; // comment
    this.ruleIds[8] = 2; // compoundExpressionConstraint
    this.ruleIds[9] = 13; // conceptId
    this.ruleIds[10] = 12; // conceptReference
    this.ruleIds[11] = 23; // conjunction
    this.ruleIds[12] = 31; // conjunctionAttributeSet
    this.ruleIds[13] = 3; // conjunctionExpressionConstraint
    this.ruleIds[14] = 27; // conjunctionRefinementSet
    this.ruleIds[15] = 16; // constraintOperator
    this.ruleIds[16] = 61; // CR
    this.ruleIds[17] = 50; // decimalValue
    this.ruleIds[18] = 17; // descendantOf
    this.ruleIds[19] = 18; // descendantOrSelfOf
    this.ruleIds[20] = 65; // digit
    this.ruleIds[21] = 67; // digitNonZero
    this.ruleIds[22] = 24; // disjunction
    this.ruleIds[23] = 32; // disjunctionAttributeSet
    this.ruleIds[24] = 4; // disjunctionExpressionConstraint
    this.ruleIds[25] = 28; // disjunctionRefinementSet
    this.ruleIds[26] = 10; // dot
    this.ruleIds[27] = 6; // dottedExpressionConstraint
    this.ruleIds[28] = 35; // eclAttribute
    this.ruleIds[29] = 34; // eclAttributeGroup
    this.ruleIds[30] = 43; // eclAttributeName
    this.ruleIds[31] = 30; // eclAttributeSet
    this.ruleIds[32] = 9; // eclFocusConcept
    this.ruleIds[33] = 26; // eclRefinement
    this.ruleIds[34] = 70; // escapedChar
    this.ruleIds[35] = 25; // exclusion
    this.ruleIds[36] = 5; // exclusionExpressionConstraint
    this.ruleIds[37] = 44; // expressionComparisonOperator
    this.ruleIds[38] = 0; // expressionConstraint
    this.ruleIds[39] = 60; // HTAB
    this.ruleIds[40] = 49; // integerValue
    this.ruleIds[41] = 62; // LF
    this.ruleIds[42] = 40; // many
    this.ruleIds[43] = 39; // maxValue
    this.ruleIds[44] = 11; // memberOf
    this.ruleIds[45] = 37; // minValue
    this.ruleIds[46] = 54; // mws
    this.ruleIds[47] = 58; // nonFSlash
    this.ruleIds[48] = 51; // nonNegativeIntegerValue
    this.ruleIds[49] = 56; // nonStarChar
    this.ruleIds[50] = 68; // nonwsNonPipe
    this.ruleIds[51] = 45; // numericComparisonOperator
    this.ruleIds[52] = 47; // numericValue
    this.ruleIds[53] = 22; // parentOf
    this.ruleIds[54] = 63; // QM
    this.ruleIds[55] = 1; // refinedExpressionConstraint
    this.ruleIds[56] = 41; // reverseFlag
    this.ruleIds[57] = 52; // sctId
    this.ruleIds[58] = 8; // simpleExpressionConstraint
    this.ruleIds[59] = 59; // SP
    this.ruleIds[60] = 57; // starWithNonFSlash
    this.ruleIds[61] = 46; // stringComparisonOperator
    this.ruleIds[62] = 48; // stringValue
    this.ruleIds[63] = 33; // subAttributeSet
    this.ruleIds[64] = 7; // subExpressionConstraint
    this.ruleIds[65] = 29; // subRefinement
    this.ruleIds[66] = 14; // term
    this.ruleIds[67] = 38; // to
    this.ruleIds[68] = 71; // UTF8-2
    this.ruleIds[69] = 72; // UTF8-3
    this.ruleIds[70] = 73; // UTF8-4
    this.ruleIds[71] = 74; // UTF8-tail
    this.ruleIds[72] = 15; // wildCard
    this.ruleIds[73] = 53; // ws
    this.ruleIds[74] = 66; // zero

    // rules
    this.rules = [];
    this.rules[0] = [];
    this.rules[0].rule = 'expressionConstraint';
    this.rules[0].lower = 'expressionconstraint';
    this.rules[0].syntax = null;
    this.rules[0].semantic = null;
    this.rules[0].opcodeIndex = 0;

    this.rules[1] = [];
    this.rules[1].rule = 'refinedExpressionConstraint';
    this.rules[1].lower = 'refinedexpressionconstraint';
    this.rules[1].syntax = null;
    this.rules[1].semantic = null;
    this.rules[1].opcodeIndex = 8;

    this.rules[2] = [];
    this.rules[2].rule = 'compoundExpressionConstraint';
    this.rules[2].lower = 'compoundexpressionconstraint';
    this.rules[2].syntax = null;
    this.rules[2].semantic = null;
    this.rules[2].opcodeIndex = 14;

    this.rules[3] = [];
    this.rules[3].rule = 'conjunctionExpressionConstraint';
    this.rules[3].lower = 'conjunctionexpressionconstraint';
    this.rules[3].syntax = null;
    this.rules[3].semantic = null;
    this.rules[3].opcodeIndex = 18;

    this.rules[4] = [];
    this.rules[4].rule = 'disjunctionExpressionConstraint';
    this.rules[4].lower = 'disjunctionexpressionconstraint';
    this.rules[4].syntax = null;
    this.rules[4].semantic = null;
    this.rules[4].opcodeIndex = 26;

    this.rules[5] = [];
    this.rules[5].rule = 'exclusionExpressionConstraint';
    this.rules[5].lower = 'exclusionexpressionconstraint';
    this.rules[5].syntax = null;
    this.rules[5].semantic = null;
    this.rules[5].opcodeIndex = 34;

    this.rules[6] = [];
    this.rules[6].rule = 'dottedExpressionConstraint';
    this.rules[6].lower = 'dottedexpressionconstraint';
    this.rules[6].syntax = null;
    this.rules[6].semantic = null;
    this.rules[6].opcodeIndex = 40;

    this.rules[7] = [];
    this.rules[7].rule = 'subExpressionConstraint';
    this.rules[7].lower = 'subexpressionconstraint';
    this.rules[7].syntax = null;
    this.rules[7].semantic = null;
    this.rules[7].opcodeIndex = 52;

    this.rules[8] = [];
    this.rules[8].rule = 'simpleExpressionConstraint';
    this.rules[8].lower = 'simpleexpressionconstraint';
    this.rules[8].syntax = null;
    this.rules[8].semantic = null;
    this.rules[8].opcodeIndex = 69;

    this.rules[9] = [];
    this.rules[9].rule = 'eclFocusConcept';
    this.rules[9].lower = 'eclfocusconcept';
    this.rules[9].syntax = null;
    this.rules[9].semantic = null;
    this.rules[9].opcodeIndex = 79;

    this.rules[10] = [];
    this.rules[10].rule = 'dot';
    this.rules[10].lower = 'dot';
    this.rules[10].syntax = null;
    this.rules[10].semantic = null;
    this.rules[10].opcodeIndex = 82;

    this.rules[11] = [];
    this.rules[11].rule = 'memberOf';
    this.rules[11].lower = 'memberof';
    this.rules[11].syntax = null;
    this.rules[11].semantic = null;
    this.rules[11].opcodeIndex = 83;

    this.rules[12] = [];
    this.rules[12].rule = 'conceptReference';
    this.rules[12].lower = 'conceptreference';
    this.rules[12].syntax = null;
    this.rules[12].semantic = null;
    this.rules[12].opcodeIndex = 84;

    this.rules[13] = [];
    this.rules[13].rule = 'conceptId';
    this.rules[13].lower = 'conceptid';
    this.rules[13].syntax = null;
    this.rules[13].semantic = null;
    this.rules[13].opcodeIndex = 94;

    this.rules[14] = [];
    this.rules[14].rule = 'term';
    this.rules[14].lower = 'term';
    this.rules[14].syntax = null;
    this.rules[14].semantic = null;
    this.rules[14].opcodeIndex = 95;

    this.rules[15] = [];
    this.rules[15].rule = 'wildCard';
    this.rules[15].lower = 'wildcard';
    this.rules[15].syntax = null;
    this.rules[15].semantic = null;
    this.rules[15].opcodeIndex = 104;

    this.rules[16] = [];
    this.rules[16].rule = 'constraintOperator';
    this.rules[16].lower = 'constraintoperator';
    this.rules[16].syntax = null;
    this.rules[16].semantic = null;
    this.rules[16].opcodeIndex = 105;

    this.rules[17] = [];
    this.rules[17].rule = 'descendantOf';
    this.rules[17].lower = 'descendantof';
    this.rules[17].syntax = null;
    this.rules[17].semantic = null;
    this.rules[17].opcodeIndex = 112;

    this.rules[18] = [];
    this.rules[18].rule = 'descendantOrSelfOf';
    this.rules[18].lower = 'descendantorselfof';
    this.rules[18].syntax = null;
    this.rules[18].semantic = null;
    this.rules[18].opcodeIndex = 113;

    this.rules[19] = [];
    this.rules[19].rule = 'childOf';
    this.rules[19].lower = 'childof';
    this.rules[19].syntax = null;
    this.rules[19].semantic = null;
    this.rules[19].opcodeIndex = 114;

    this.rules[20] = [];
    this.rules[20].rule = 'ancestorOf';
    this.rules[20].lower = 'ancestorof';
    this.rules[20].syntax = null;
    this.rules[20].semantic = null;
    this.rules[20].opcodeIndex = 115;

    this.rules[21] = [];
    this.rules[21].rule = 'ancestorOrSelfOf';
    this.rules[21].lower = 'ancestororselfof';
    this.rules[21].syntax = null;
    this.rules[21].semantic = null;
    this.rules[21].opcodeIndex = 116;

    this.rules[22] = [];
    this.rules[22].rule = 'parentOf';
    this.rules[22].lower = 'parentof';
    this.rules[22].syntax = null;
    this.rules[22].semantic = null;
    this.rules[22].opcodeIndex = 117;

    this.rules[23] = [];
    this.rules[23].rule = 'conjunction';
    this.rules[23].lower = 'conjunction';
    this.rules[23].syntax = null;
    this.rules[23].semantic = null;
    this.rules[23].opcodeIndex = 118;

    this.rules[24] = [];
    this.rules[24].rule = 'disjunction';
    this.rules[24].lower = 'disjunction';
    this.rules[24].syntax = null;
    this.rules[24].semantic = null;
    this.rules[24].opcodeIndex = 131;

    this.rules[25] = [];
    this.rules[25].rule = 'exclusion';
    this.rules[25].lower = 'exclusion';
    this.rules[25].syntax = null;
    this.rules[25].semantic = null;
    this.rules[25].opcodeIndex = 139;

    this.rules[26] = [];
    this.rules[26].rule = 'eclRefinement';
    this.rules[26].lower = 'eclrefinement';
    this.rules[26].syntax = null;
    this.rules[26].semantic = null;
    this.rules[26].opcodeIndex = 156;

    this.rules[27] = [];
    this.rules[27].rule = 'conjunctionRefinementSet';
    this.rules[27].lower = 'conjunctionrefinementset';
    this.rules[27].syntax = null;
    this.rules[27].semantic = null;
    this.rules[27].opcodeIndex = 163;

    this.rules[28] = [];
    this.rules[28].rule = 'disjunctionRefinementSet';
    this.rules[28].lower = 'disjunctionrefinementset';
    this.rules[28].syntax = null;
    this.rules[28].semantic = null;
    this.rules[28].opcodeIndex = 169;

    this.rules[29] = [];
    this.rules[29].rule = 'subRefinement';
    this.rules[29].lower = 'subrefinement';
    this.rules[29].syntax = null;
    this.rules[29].semantic = null;
    this.rules[29].opcodeIndex = 175;

    this.rules[30] = [];
    this.rules[30].rule = 'eclAttributeSet';
    this.rules[30].lower = 'eclattributeset';
    this.rules[30].syntax = null;
    this.rules[30].semantic = null;
    this.rules[30].opcodeIndex = 184;

    this.rules[31] = [];
    this.rules[31].rule = 'conjunctionAttributeSet';
    this.rules[31].lower = 'conjunctionattributeset';
    this.rules[31].syntax = null;
    this.rules[31].semantic = null;
    this.rules[31].opcodeIndex = 191;

    this.rules[32] = [];
    this.rules[32].rule = 'disjunctionAttributeSet';
    this.rules[32].lower = 'disjunctionattributeset';
    this.rules[32].syntax = null;
    this.rules[32].semantic = null;
    this.rules[32].opcodeIndex = 197;

    this.rules[33] = [];
    this.rules[33].rule = 'subAttributeSet';
    this.rules[33].lower = 'subattributeset';
    this.rules[33].syntax = null;
    this.rules[33].semantic = null;
    this.rules[33].opcodeIndex = 203;

    this.rules[34] = [];
    this.rules[34].rule = 'eclAttributeGroup';
    this.rules[34].lower = 'eclattributegroup';
    this.rules[34].syntax = null;
    this.rules[34].semantic = null;
    this.rules[34].opcodeIndex = 211;

    this.rules[35] = [];
    this.rules[35].rule = 'eclAttribute';
    this.rules[35].lower = 'eclattribute';
    this.rules[35].syntax = null;
    this.rules[35].semantic = null;
    this.rules[35].opcodeIndex = 223;

    this.rules[36] = [];
    this.rules[36].rule = 'cardinality';
    this.rules[36].lower = 'cardinality';
    this.rules[36].syntax = null;
    this.rules[36].semantic = null;
    this.rules[36].opcodeIndex = 256;

    this.rules[37] = [];
    this.rules[37].rule = 'minValue';
    this.rules[37].lower = 'minvalue';
    this.rules[37].syntax = null;
    this.rules[37].semantic = null;
    this.rules[37].opcodeIndex = 260;

    this.rules[38] = [];
    this.rules[38].rule = 'to';
    this.rules[38].lower = 'to';
    this.rules[38].syntax = null;
    this.rules[38].semantic = null;
    this.rules[38].opcodeIndex = 261;

    this.rules[39] = [];
    this.rules[39].rule = 'maxValue';
    this.rules[39].lower = 'maxvalue';
    this.rules[39].syntax = null;
    this.rules[39].semantic = null;
    this.rules[39].opcodeIndex = 262;

    this.rules[40] = [];
    this.rules[40].rule = 'many';
    this.rules[40].lower = 'many';
    this.rules[40].syntax = null;
    this.rules[40].semantic = null;
    this.rules[40].opcodeIndex = 265;

    this.rules[41] = [];
    this.rules[41].rule = 'reverseFlag';
    this.rules[41].lower = 'reverseflag';
    this.rules[41].syntax = null;
    this.rules[41].semantic = null;
    this.rules[41].opcodeIndex = 266;

    this.rules[42] = [];
    this.rules[42].rule = 'attributeOperator';
    this.rules[42].lower = 'attributeoperator';
    this.rules[42].syntax = null;
    this.rules[42].semantic = null;
    this.rules[42].opcodeIndex = 267;

    this.rules[43] = [];
    this.rules[43].rule = 'eclAttributeName';
    this.rules[43].lower = 'eclattributename';
    this.rules[43].syntax = null;
    this.rules[43].semantic = null;
    this.rules[43].opcodeIndex = 270;

    this.rules[44] = [];
    this.rules[44].rule = 'expressionComparisonOperator';
    this.rules[44].lower = 'expressioncomparisonoperator';
    this.rules[44].syntax = null;
    this.rules[44].semantic = null;
    this.rules[44].opcodeIndex = 273;

    this.rules[45] = [];
    this.rules[45].rule = 'numericComparisonOperator';
    this.rules[45].lower = 'numericcomparisonoperator';
    this.rules[45].syntax = null;
    this.rules[45].semantic = null;
    this.rules[45].opcodeIndex = 276;

    this.rules[46] = [];
    this.rules[46].rule = 'stringComparisonOperator';
    this.rules[46].lower = 'stringcomparisonoperator';
    this.rules[46].syntax = null;
    this.rules[46].semantic = null;
    this.rules[46].opcodeIndex = 283;

    this.rules[47] = [];
    this.rules[47].rule = 'numericValue';
    this.rules[47].lower = 'numericvalue';
    this.rules[47].syntax = null;
    this.rules[47].semantic = null;
    this.rules[47].opcodeIndex = 286;

    this.rules[48] = [];
    this.rules[48].rule = 'stringValue';
    this.rules[48].lower = 'stringvalue';
    this.rules[48].syntax = null;
    this.rules[48].semantic = null;
    this.rules[48].opcodeIndex = 294;

    this.rules[49] = [];
    this.rules[49].rule = 'integerValue';
    this.rules[49].lower = 'integervalue';
    this.rules[49].syntax = null;
    this.rules[49].semantic = null;
    this.rules[49].opcodeIndex = 298;

    this.rules[50] = [];
    this.rules[50].rule = 'decimalValue';
    this.rules[50].lower = 'decimalvalue';
    this.rules[50].syntax = null;
    this.rules[50].semantic = null;
    this.rules[50].opcodeIndex = 304;

    this.rules[51] = [];
    this.rules[51].rule = 'nonNegativeIntegerValue';
    this.rules[51].lower = 'nonnegativeintegervalue';
    this.rules[51].syntax = null;
    this.rules[51].semantic = null;
    this.rules[51].opcodeIndex = 309;

    this.rules[52] = [];
    this.rules[52].rule = 'sctId';
    this.rules[52].lower = 'sctid';
    this.rules[52].syntax = null;
    this.rules[52].semantic = null;
    this.rules[52].opcodeIndex = 315;

    this.rules[53] = [];
    this.rules[53].rule = 'ws';
    this.rules[53].lower = 'ws';
    this.rules[53].syntax = null;
    this.rules[53].semantic = null;
    this.rules[53].opcodeIndex = 319;

    this.rules[54] = [];
    this.rules[54].rule = 'mws';
    this.rules[54].lower = 'mws';
    this.rules[54].syntax = null;
    this.rules[54].semantic = null;
    this.rules[54].opcodeIndex = 326;

    this.rules[55] = [];
    this.rules[55].rule = 'comment';
    this.rules[55].lower = 'comment';
    this.rules[55].syntax = null;
    this.rules[55].semantic = null;
    this.rules[55].opcodeIndex = 333;

    this.rules[56] = [];
    this.rules[56].rule = 'nonStarChar';
    this.rules[56].lower = 'nonstarchar';
    this.rules[56].syntax = null;
    this.rules[56].semantic = null;
    this.rules[56].opcodeIndex = 340;

    this.rules[57] = [];
    this.rules[57].rule = 'starWithNonFSlash';
    this.rules[57].lower = 'starwithnonfslash';
    this.rules[57].syntax = null;
    this.rules[57].semantic = null;
    this.rules[57].opcodeIndex = 350;

    this.rules[58] = [];
    this.rules[58].rule = 'nonFSlash';
    this.rules[58].lower = 'nonfslash';
    this.rules[58].syntax = null;
    this.rules[58].semantic = null;
    this.rules[58].opcodeIndex = 353;

    this.rules[59] = [];
    this.rules[59].rule = 'SP';
    this.rules[59].lower = 'sp';
    this.rules[59].syntax = null;
    this.rules[59].semantic = null;
    this.rules[59].opcodeIndex = 363;

    this.rules[60] = [];
    this.rules[60].rule = 'HTAB';
    this.rules[60].lower = 'htab';
    this.rules[60].syntax = null;
    this.rules[60].semantic = null;
    this.rules[60].opcodeIndex = 364;

    this.rules[61] = [];
    this.rules[61].rule = 'CR';
    this.rules[61].lower = 'cr';
    this.rules[61].syntax = null;
    this.rules[61].semantic = null;
    this.rules[61].opcodeIndex = 365;

    this.rules[62] = [];
    this.rules[62].rule = 'LF';
    this.rules[62].lower = 'lf';
    this.rules[62].syntax = null;
    this.rules[62].semantic = null;
    this.rules[62].opcodeIndex = 366;

    this.rules[63] = [];
    this.rules[63].rule = 'QM';
    this.rules[63].lower = 'qm';
    this.rules[63].syntax = null;
    this.rules[63].semantic = null;
    this.rules[63].opcodeIndex = 367;

    this.rules[64] = [];
    this.rules[64].rule = 'BS';
    this.rules[64].lower = 'bs';
    this.rules[64].syntax = null;
    this.rules[64].semantic = null;
    this.rules[64].opcodeIndex = 368;

    this.rules[65] = [];
    this.rules[65].rule = 'digit';
    this.rules[65].lower = 'digit';
    this.rules[65].syntax = null;
    this.rules[65].semantic = null;
    this.rules[65].opcodeIndex = 369;

    this.rules[66] = [];
    this.rules[66].rule = 'zero';
    this.rules[66].lower = 'zero';
    this.rules[66].syntax = null;
    this.rules[66].semantic = null;
    this.rules[66].opcodeIndex = 370;

    this.rules[67] = [];
    this.rules[67].rule = 'digitNonZero';
    this.rules[67].lower = 'digitnonzero';
    this.rules[67].syntax = null;
    this.rules[67].semantic = null;
    this.rules[67].opcodeIndex = 371;

    this.rules[68] = [];
    this.rules[68].rule = 'nonwsNonPipe';
    this.rules[68].lower = 'nonwsnonpipe';
    this.rules[68].syntax = null;
    this.rules[68].semantic = null;
    this.rules[68].opcodeIndex = 372;

    this.rules[69] = [];
    this.rules[69].rule = 'anyNonEscapedChar';
    this.rules[69].lower = 'anynonescapedchar';
    this.rules[69].syntax = null;
    this.rules[69].semantic = null;
    this.rules[69].opcodeIndex = 378;

    this.rules[70] = [];
    this.rules[70].rule = 'escapedChar';
    this.rules[70].lower = 'escapedchar';
    this.rules[70].syntax = null;
    this.rules[70].semantic = null;
    this.rules[70].opcodeIndex = 389;

    this.rules[71] = [];
    this.rules[71].rule = 'UTF8-2';
    this.rules[71].lower = 'utf8-2';
    this.rules[71].syntax = null;
    this.rules[71].semantic = null;
    this.rules[71].opcodeIndex = 396;

    this.rules[72] = [];
    this.rules[72].rule = 'UTF8-3';
    this.rules[72].lower = 'utf8-3';
    this.rules[72].syntax = null;
    this.rules[72].semantic = null;
    this.rules[72].opcodeIndex = 399;

    this.rules[73] = [];
    this.rules[73].rule = 'UTF8-4';
    this.rules[73].lower = 'utf8-4';
    this.rules[73].syntax = null;
    this.rules[73].semantic = null;
    this.rules[73].opcodeIndex = 416;

    this.rules[74] = [];
    this.rules[74].rule = 'UTF8-tail';
    this.rules[74].lower = 'utf8-tail';
    this.rules[74].syntax = null;
    this.rules[74].semantic = null;
    this.rules[74].opcodeIndex = 431;

    // opcodes
    this.opcodes = [];
    this.opcodes[0] = [];
    this.opcodes[0].opNext = 8;
    this.opcodes[0].type = CAT;

    this.opcodes[1] = [];
    this.opcodes[1].opNext = 2;
    this.opcodes[1].type = RNM;
    this.opcodes[1].ruleIndex = 53;

    this.opcodes[2] = [];
    this.opcodes[2].opNext = 7;
    this.opcodes[2].type = ALT;

    this.opcodes[3] = [];
    this.opcodes[3].opNext = 4;
    this.opcodes[3].type = RNM;
    this.opcodes[3].ruleIndex = 1;

    this.opcodes[4] = [];
    this.opcodes[4].opNext = 5;
    this.opcodes[4].type = RNM;
    this.opcodes[4].ruleIndex = 2;

    this.opcodes[5] = [];
    this.opcodes[5].opNext = 6;
    this.opcodes[5].type = RNM;
    this.opcodes[5].ruleIndex = 6;

    this.opcodes[6] = [];
    this.opcodes[6].opNext = 7;
    this.opcodes[6].type = RNM;
    this.opcodes[6].ruleIndex = 7;

    this.opcodes[7] = [];
    this.opcodes[7].opNext = 8;
    this.opcodes[7].type = RNM;
    this.opcodes[7].ruleIndex = 53;

    this.opcodes[8] = [];
    this.opcodes[8].opNext = 14;
    this.opcodes[8].type = CAT;

    this.opcodes[9] = [];
    this.opcodes[9].opNext = 10;
    this.opcodes[9].type = RNM;
    this.opcodes[9].ruleIndex = 8;

    this.opcodes[10] = [];
    this.opcodes[10].opNext = 11;
    this.opcodes[10].type = RNM;
    this.opcodes[10].ruleIndex = 53;

    this.opcodes[11] = [];
    this.opcodes[11].opNext = 12;
    this.opcodes[11].type = TLS;
    this.opcodes[11].length = 1;
    this.opcodes[11].stringIndex = 0;

    this.opcodes[12] = [];
    this.opcodes[12].opNext = 13;
    this.opcodes[12].type = RNM;
    this.opcodes[12].ruleIndex = 53;

    this.opcodes[13] = [];
    this.opcodes[13].opNext = 14;
    this.opcodes[13].type = RNM;
    this.opcodes[13].ruleIndex = 26;

    this.opcodes[14] = [];
    this.opcodes[14].opNext = 18;
    this.opcodes[14].type = ALT;

    this.opcodes[15] = [];
    this.opcodes[15].opNext = 16;
    this.opcodes[15].type = RNM;
    this.opcodes[15].ruleIndex = 3;

    this.opcodes[16] = [];
    this.opcodes[16].opNext = 17;
    this.opcodes[16].type = RNM;
    this.opcodes[16].ruleIndex = 4;

    this.opcodes[17] = [];
    this.opcodes[17].opNext = 18;
    this.opcodes[17].type = RNM;
    this.opcodes[17].ruleIndex = 5;

    this.opcodes[18] = [];
    this.opcodes[18].opNext = 26;
    this.opcodes[18].type = CAT;

    this.opcodes[19] = [];
    this.opcodes[19].opNext = 20;
    this.opcodes[19].type = RNM;
    this.opcodes[19].ruleIndex = 7;

    this.opcodes[20] = [];
    this.opcodes[20].opNext = 26;
    this.opcodes[20].type = REP;
    this.opcodes[20].min = 1;
    this.opcodes[20].max = Infinity;

    this.opcodes[21] = [];
    this.opcodes[21].opNext = 26;
    this.opcodes[21].type = CAT;

    this.opcodes[22] = [];
    this.opcodes[22].opNext = 23;
    this.opcodes[22].type = RNM;
    this.opcodes[22].ruleIndex = 53;

    this.opcodes[23] = [];
    this.opcodes[23].opNext = 24;
    this.opcodes[23].type = RNM;
    this.opcodes[23].ruleIndex = 23;

    this.opcodes[24] = [];
    this.opcodes[24].opNext = 25;
    this.opcodes[24].type = RNM;
    this.opcodes[24].ruleIndex = 53;

    this.opcodes[25] = [];
    this.opcodes[25].opNext = 26;
    this.opcodes[25].type = RNM;
    this.opcodes[25].ruleIndex = 7;

    this.opcodes[26] = [];
    this.opcodes[26].opNext = 34;
    this.opcodes[26].type = CAT;

    this.opcodes[27] = [];
    this.opcodes[27].opNext = 28;
    this.opcodes[27].type = RNM;
    this.opcodes[27].ruleIndex = 7;

    this.opcodes[28] = [];
    this.opcodes[28].opNext = 34;
    this.opcodes[28].type = REP;
    this.opcodes[28].min = 1;
    this.opcodes[28].max = Infinity;

    this.opcodes[29] = [];
    this.opcodes[29].opNext = 34;
    this.opcodes[29].type = CAT;

    this.opcodes[30] = [];
    this.opcodes[30].opNext = 31;
    this.opcodes[30].type = RNM;
    this.opcodes[30].ruleIndex = 53;

    this.opcodes[31] = [];
    this.opcodes[31].opNext = 32;
    this.opcodes[31].type = RNM;
    this.opcodes[31].ruleIndex = 24;

    this.opcodes[32] = [];
    this.opcodes[32].opNext = 33;
    this.opcodes[32].type = RNM;
    this.opcodes[32].ruleIndex = 53;

    this.opcodes[33] = [];
    this.opcodes[33].opNext = 34;
    this.opcodes[33].type = RNM;
    this.opcodes[33].ruleIndex = 7;

    this.opcodes[34] = [];
    this.opcodes[34].opNext = 40;
    this.opcodes[34].type = CAT;

    this.opcodes[35] = [];
    this.opcodes[35].opNext = 36;
    this.opcodes[35].type = RNM;
    this.opcodes[35].ruleIndex = 7;

    this.opcodes[36] = [];
    this.opcodes[36].opNext = 37;
    this.opcodes[36].type = RNM;
    this.opcodes[36].ruleIndex = 53;

    this.opcodes[37] = [];
    this.opcodes[37].opNext = 38;
    this.opcodes[37].type = RNM;
    this.opcodes[37].ruleIndex = 25;

    this.opcodes[38] = [];
    this.opcodes[38].opNext = 39;
    this.opcodes[38].type = RNM;
    this.opcodes[38].ruleIndex = 53;

    this.opcodes[39] = [];
    this.opcodes[39].opNext = 40;
    this.opcodes[39].type = RNM;
    this.opcodes[39].ruleIndex = 7;

    this.opcodes[40] = [];
    this.opcodes[40].opNext = 52;
    this.opcodes[40].type = CAT;

    this.opcodes[41] = [];
    this.opcodes[41].opNext = 42;
    this.opcodes[41].type = RNM;
    this.opcodes[41].ruleIndex = 7;

    this.opcodes[42] = [];
    this.opcodes[42].opNext = 52;
    this.opcodes[42].type = REP;
    this.opcodes[42].min = 1;
    this.opcodes[42].max = Infinity;

    this.opcodes[43] = [];
    this.opcodes[43].opNext = 52;
    this.opcodes[43].type = CAT;

    this.opcodes[44] = [];
    this.opcodes[44].opNext = 45;
    this.opcodes[44].type = RNM;
    this.opcodes[44].ruleIndex = 53;

    this.opcodes[45] = [];
    this.opcodes[45].opNext = 46;
    this.opcodes[45].type = RNM;
    this.opcodes[45].ruleIndex = 10;

    this.opcodes[46] = [];
    this.opcodes[46].opNext = 47;
    this.opcodes[46].type = RNM;
    this.opcodes[46].ruleIndex = 53;

    this.opcodes[47] = [];
    this.opcodes[47].opNext = 51;
    this.opcodes[47].type = REP;
    this.opcodes[47].min = 0;
    this.opcodes[47].max = 1;

    this.opcodes[48] = [];
    this.opcodes[48].opNext = 51;
    this.opcodes[48].type = CAT;

    this.opcodes[49] = [];
    this.opcodes[49].opNext = 50;
    this.opcodes[49].type = RNM;
    this.opcodes[49].ruleIndex = 42;

    this.opcodes[50] = [];
    this.opcodes[50].opNext = 51;
    this.opcodes[50].type = RNM;
    this.opcodes[50].ruleIndex = 53;

    this.opcodes[51] = [];
    this.opcodes[51].opNext = 52;
    this.opcodes[51].type = RNM;
    this.opcodes[51].ruleIndex = 43;

    this.opcodes[52] = [];
    this.opcodes[52].opNext = 69;
    this.opcodes[52].type = CAT;

    this.opcodes[53] = [];
    this.opcodes[53].opNext = 57;
    this.opcodes[53].type = REP;
    this.opcodes[53].min = 0;
    this.opcodes[53].max = 1;

    this.opcodes[54] = [];
    this.opcodes[54].opNext = 57;
    this.opcodes[54].type = CAT;

    this.opcodes[55] = [];
    this.opcodes[55].opNext = 56;
    this.opcodes[55].type = RNM;
    this.opcodes[55].ruleIndex = 16;

    this.opcodes[56] = [];
    this.opcodes[56].opNext = 57;
    this.opcodes[56].type = RNM;
    this.opcodes[56].ruleIndex = 53;

    this.opcodes[57] = [];
    this.opcodes[57].opNext = 61;
    this.opcodes[57].type = REP;
    this.opcodes[57].min = 0;
    this.opcodes[57].max = 1;

    this.opcodes[58] = [];
    this.opcodes[58].opNext = 61;
    this.opcodes[58].type = CAT;

    this.opcodes[59] = [];
    this.opcodes[59].opNext = 60;
    this.opcodes[59].type = RNM;
    this.opcodes[59].ruleIndex = 11;

    this.opcodes[60] = [];
    this.opcodes[60].opNext = 61;
    this.opcodes[60].type = RNM;
    this.opcodes[60].ruleIndex = 53;

    this.opcodes[61] = [];
    this.opcodes[61].opNext = 69;
    this.opcodes[61].type = ALT;

    this.opcodes[62] = [];
    this.opcodes[62].opNext = 63;
    this.opcodes[62].type = RNM;
    this.opcodes[62].ruleIndex = 9;

    this.opcodes[63] = [];
    this.opcodes[63].opNext = 69;
    this.opcodes[63].type = CAT;

    this.opcodes[64] = [];
    this.opcodes[64].opNext = 65;
    this.opcodes[64].type = TLS;
    this.opcodes[64].length = 1;
    this.opcodes[64].stringIndex = 1;

    this.opcodes[65] = [];
    this.opcodes[65].opNext = 66;
    this.opcodes[65].type = RNM;
    this.opcodes[65].ruleIndex = 53;

    this.opcodes[66] = [];
    this.opcodes[66].opNext = 67;
    this.opcodes[66].type = RNM;
    this.opcodes[66].ruleIndex = 0;

    this.opcodes[67] = [];
    this.opcodes[67].opNext = 68;
    this.opcodes[67].type = RNM;
    this.opcodes[67].ruleIndex = 53;

    this.opcodes[68] = [];
    this.opcodes[68].opNext = 69;
    this.opcodes[68].type = TLS;
    this.opcodes[68].length = 1;
    this.opcodes[68].stringIndex = 2;

    this.opcodes[69] = [];
    this.opcodes[69].opNext = 79;
    this.opcodes[69].type = CAT;

    this.opcodes[70] = [];
    this.opcodes[70].opNext = 74;
    this.opcodes[70].type = REP;
    this.opcodes[70].min = 0;
    this.opcodes[70].max = 1;

    this.opcodes[71] = [];
    this.opcodes[71].opNext = 74;
    this.opcodes[71].type = CAT;

    this.opcodes[72] = [];
    this.opcodes[72].opNext = 73;
    this.opcodes[72].type = RNM;
    this.opcodes[72].ruleIndex = 16;

    this.opcodes[73] = [];
    this.opcodes[73].opNext = 74;
    this.opcodes[73].type = RNM;
    this.opcodes[73].ruleIndex = 53;

    this.opcodes[74] = [];
    this.opcodes[74].opNext = 78;
    this.opcodes[74].type = REP;
    this.opcodes[74].min = 0;
    this.opcodes[74].max = 1;

    this.opcodes[75] = [];
    this.opcodes[75].opNext = 78;
    this.opcodes[75].type = CAT;

    this.opcodes[76] = [];
    this.opcodes[76].opNext = 77;
    this.opcodes[76].type = RNM;
    this.opcodes[76].ruleIndex = 11;

    this.opcodes[77] = [];
    this.opcodes[77].opNext = 78;
    this.opcodes[77].type = RNM;
    this.opcodes[77].ruleIndex = 53;

    this.opcodes[78] = [];
    this.opcodes[78].opNext = 79;
    this.opcodes[78].type = RNM;
    this.opcodes[78].ruleIndex = 9;

    this.opcodes[79] = [];
    this.opcodes[79].opNext = 82;
    this.opcodes[79].type = ALT;

    this.opcodes[80] = [];
    this.opcodes[80].opNext = 81;
    this.opcodes[80].type = RNM;
    this.opcodes[80].ruleIndex = 12;

    this.opcodes[81] = [];
    this.opcodes[81].opNext = 82;
    this.opcodes[81].type = RNM;
    this.opcodes[81].ruleIndex = 15;

    this.opcodes[82] = [];
    this.opcodes[82].opNext = 83;
    this.opcodes[82].type = TLS;
    this.opcodes[82].length = 1;
    this.opcodes[82].stringIndex = 3;

    this.opcodes[83] = [];
    this.opcodes[83].opNext = 84;
    this.opcodes[83].type = TLS;
    this.opcodes[83].length = 1;
    this.opcodes[83].stringIndex = 4;

    this.opcodes[84] = [];
    this.opcodes[84].opNext = 94;
    this.opcodes[84].type = CAT;

    this.opcodes[85] = [];
    this.opcodes[85].opNext = 86;
    this.opcodes[85].type = RNM;
    this.opcodes[85].ruleIndex = 13;

    this.opcodes[86] = [];
    this.opcodes[86].opNext = 94;
    this.opcodes[86].type = REP;
    this.opcodes[86].min = 0;
    this.opcodes[86].max = 1;

    this.opcodes[87] = [];
    this.opcodes[87].opNext = 94;
    this.opcodes[87].type = CAT;

    this.opcodes[88] = [];
    this.opcodes[88].opNext = 89;
    this.opcodes[88].type = RNM;
    this.opcodes[88].ruleIndex = 53;

    this.opcodes[89] = [];
    this.opcodes[89].opNext = 90;
    this.opcodes[89].type = TLS;
    this.opcodes[89].length = 1;
    this.opcodes[89].stringIndex = 5;

    this.opcodes[90] = [];
    this.opcodes[90].opNext = 91;
    this.opcodes[90].type = RNM;
    this.opcodes[90].ruleIndex = 53;

    this.opcodes[91] = [];
    this.opcodes[91].opNext = 92;
    this.opcodes[91].type = RNM;
    this.opcodes[91].ruleIndex = 14;

    this.opcodes[92] = [];
    this.opcodes[92].opNext = 93;
    this.opcodes[92].type = RNM;
    this.opcodes[92].ruleIndex = 53;

    this.opcodes[93] = [];
    this.opcodes[93].opNext = 94;
    this.opcodes[93].type = TLS;
    this.opcodes[93].length = 1;
    this.opcodes[93].stringIndex = 6;

    this.opcodes[94] = [];
    this.opcodes[94].opNext = 95;
    this.opcodes[94].type = RNM;
    this.opcodes[94].ruleIndex = 52;

    this.opcodes[95] = [];
    this.opcodes[95].opNext = 104;
    this.opcodes[95].type = CAT;

    this.opcodes[96] = [];
    this.opcodes[96].opNext = 98;
    this.opcodes[96].type = REP;
    this.opcodes[96].min = 1;
    this.opcodes[96].max = Infinity;

    this.opcodes[97] = [];
    this.opcodes[97].opNext = 98;
    this.opcodes[97].type = RNM;
    this.opcodes[97].ruleIndex = 68;

    this.opcodes[98] = [];
    this.opcodes[98].opNext = 104;
    this.opcodes[98].type = REP;
    this.opcodes[98].min = 0;
    this.opcodes[98].max = Infinity;

    this.opcodes[99] = [];
    this.opcodes[99].opNext = 104;
    this.opcodes[99].type = CAT;

    this.opcodes[100] = [];
    this.opcodes[100].opNext = 102;
    this.opcodes[100].type = REP;
    this.opcodes[100].min = 1;
    this.opcodes[100].max = Infinity;

    this.opcodes[101] = [];
    this.opcodes[101].opNext = 102;
    this.opcodes[101].type = RNM;
    this.opcodes[101].ruleIndex = 59;

    this.opcodes[102] = [];
    this.opcodes[102].opNext = 104;
    this.opcodes[102].type = REP;
    this.opcodes[102].min = 1;
    this.opcodes[102].max = Infinity;

    this.opcodes[103] = [];
    this.opcodes[103].opNext = 104;
    this.opcodes[103].type = RNM;
    this.opcodes[103].ruleIndex = 68;

    this.opcodes[104] = [];
    this.opcodes[104].opNext = 105;
    this.opcodes[104].type = TLS;
    this.opcodes[104].length = 1;
    this.opcodes[104].stringIndex = 7;

    this.opcodes[105] = [];
    this.opcodes[105].opNext = 112;
    this.opcodes[105].type = ALT;

    this.opcodes[106] = [];
    this.opcodes[106].opNext = 107;
    this.opcodes[106].type = RNM;
    this.opcodes[106].ruleIndex = 19;

    this.opcodes[107] = [];
    this.opcodes[107].opNext = 108;
    this.opcodes[107].type = RNM;
    this.opcodes[107].ruleIndex = 18;

    this.opcodes[108] = [];
    this.opcodes[108].opNext = 109;
    this.opcodes[108].type = RNM;
    this.opcodes[108].ruleIndex = 17;

    this.opcodes[109] = [];
    this.opcodes[109].opNext = 110;
    this.opcodes[109].type = RNM;
    this.opcodes[109].ruleIndex = 22;

    this.opcodes[110] = [];
    this.opcodes[110].opNext = 111;
    this.opcodes[110].type = RNM;
    this.opcodes[110].ruleIndex = 21;

    this.opcodes[111] = [];
    this.opcodes[111].opNext = 112;
    this.opcodes[111].type = RNM;
    this.opcodes[111].ruleIndex = 20;

    this.opcodes[112] = [];
    this.opcodes[112].opNext = 113;
    this.opcodes[112].type = TLS;
    this.opcodes[112].length = 1;
    this.opcodes[112].stringIndex = 8;

    this.opcodes[113] = [];
    this.opcodes[113].opNext = 114;
    this.opcodes[113].type = TLS;
    this.opcodes[113].length = 2;
    this.opcodes[113].stringIndex = 9;

    this.opcodes[114] = [];
    this.opcodes[114].opNext = 115;
    this.opcodes[114].type = TLS;
    this.opcodes[114].length = 2;
    this.opcodes[114].stringIndex = 11;

    this.opcodes[115] = [];
    this.opcodes[115].opNext = 116;
    this.opcodes[115].type = TLS;
    this.opcodes[115].length = 1;
    this.opcodes[115].stringIndex = 13;

    this.opcodes[116] = [];
    this.opcodes[116].opNext = 117;
    this.opcodes[116].type = TLS;
    this.opcodes[116].length = 2;
    this.opcodes[116].stringIndex = 14;

    this.opcodes[117] = [];
    this.opcodes[117].opNext = 118;
    this.opcodes[117].type = TLS;
    this.opcodes[117].length = 2;
    this.opcodes[117].stringIndex = 16;

    this.opcodes[118] = [];
    this.opcodes[118].opNext = 131;
    this.opcodes[118].type = ALT;

    this.opcodes[119] = [];
    this.opcodes[119].opNext = 130;
    this.opcodes[119].type = CAT;

    this.opcodes[120] = [];
    this.opcodes[120].opNext = 123;
    this.opcodes[120].type = ALT;

    this.opcodes[121] = [];
    this.opcodes[121].opNext = 122;
    this.opcodes[121].type = TLS;
    this.opcodes[121].length = 1;
    this.opcodes[121].stringIndex = 18;

    this.opcodes[122] = [];
    this.opcodes[122].opNext = 123;
    this.opcodes[122].type = TLS;
    this.opcodes[122].length = 1;
    this.opcodes[122].stringIndex = 19;

    this.opcodes[123] = [];
    this.opcodes[123].opNext = 126;
    this.opcodes[123].type = ALT;

    this.opcodes[124] = [];
    this.opcodes[124].opNext = 125;
    this.opcodes[124].type = TLS;
    this.opcodes[124].length = 1;
    this.opcodes[124].stringIndex = 20;

    this.opcodes[125] = [];
    this.opcodes[125].opNext = 126;
    this.opcodes[125].type = TLS;
    this.opcodes[125].length = 1;
    this.opcodes[125].stringIndex = 21;

    this.opcodes[126] = [];
    this.opcodes[126].opNext = 129;
    this.opcodes[126].type = ALT;

    this.opcodes[127] = [];
    this.opcodes[127].opNext = 128;
    this.opcodes[127].type = TLS;
    this.opcodes[127].length = 1;
    this.opcodes[127].stringIndex = 22;

    this.opcodes[128] = [];
    this.opcodes[128].opNext = 129;
    this.opcodes[128].type = TLS;
    this.opcodes[128].length = 1;
    this.opcodes[128].stringIndex = 23;

    this.opcodes[129] = [];
    this.opcodes[129].opNext = 130;
    this.opcodes[129].type = RNM;
    this.opcodes[129].ruleIndex = 54;

    this.opcodes[130] = [];
    this.opcodes[130].opNext = 131;
    this.opcodes[130].type = TLS;
    this.opcodes[130].length = 1;
    this.opcodes[130].stringIndex = 24;

    this.opcodes[131] = [];
    this.opcodes[131].opNext = 139;
    this.opcodes[131].type = CAT;

    this.opcodes[132] = [];
    this.opcodes[132].opNext = 135;
    this.opcodes[132].type = ALT;

    this.opcodes[133] = [];
    this.opcodes[133].opNext = 134;
    this.opcodes[133].type = TLS;
    this.opcodes[133].length = 1;
    this.opcodes[133].stringIndex = 25;

    this.opcodes[134] = [];
    this.opcodes[134].opNext = 135;
    this.opcodes[134].type = TLS;
    this.opcodes[134].length = 1;
    this.opcodes[134].stringIndex = 26;

    this.opcodes[135] = [];
    this.opcodes[135].opNext = 138;
    this.opcodes[135].type = ALT;

    this.opcodes[136] = [];
    this.opcodes[136].opNext = 137;
    this.opcodes[136].type = TLS;
    this.opcodes[136].length = 1;
    this.opcodes[136].stringIndex = 27;

    this.opcodes[137] = [];
    this.opcodes[137].opNext = 138;
    this.opcodes[137].type = TLS;
    this.opcodes[137].length = 1;
    this.opcodes[137].stringIndex = 28;

    this.opcodes[138] = [];
    this.opcodes[138].opNext = 139;
    this.opcodes[138].type = RNM;
    this.opcodes[138].ruleIndex = 54;

    this.opcodes[139] = [];
    this.opcodes[139].opNext = 156;
    this.opcodes[139].type = CAT;

    this.opcodes[140] = [];
    this.opcodes[140].opNext = 143;
    this.opcodes[140].type = ALT;

    this.opcodes[141] = [];
    this.opcodes[141].opNext = 142;
    this.opcodes[141].type = TLS;
    this.opcodes[141].length = 1;
    this.opcodes[141].stringIndex = 29;

    this.opcodes[142] = [];
    this.opcodes[142].opNext = 143;
    this.opcodes[142].type = TLS;
    this.opcodes[142].length = 1;
    this.opcodes[142].stringIndex = 30;

    this.opcodes[143] = [];
    this.opcodes[143].opNext = 146;
    this.opcodes[143].type = ALT;

    this.opcodes[144] = [];
    this.opcodes[144].opNext = 145;
    this.opcodes[144].type = TLS;
    this.opcodes[144].length = 1;
    this.opcodes[144].stringIndex = 31;

    this.opcodes[145] = [];
    this.opcodes[145].opNext = 146;
    this.opcodes[145].type = TLS;
    this.opcodes[145].length = 1;
    this.opcodes[145].stringIndex = 32;

    this.opcodes[146] = [];
    this.opcodes[146].opNext = 149;
    this.opcodes[146].type = ALT;

    this.opcodes[147] = [];
    this.opcodes[147].opNext = 148;
    this.opcodes[147].type = TLS;
    this.opcodes[147].length = 1;
    this.opcodes[147].stringIndex = 33;

    this.opcodes[148] = [];
    this.opcodes[148].opNext = 149;
    this.opcodes[148].type = TLS;
    this.opcodes[148].length = 1;
    this.opcodes[148].stringIndex = 34;

    this.opcodes[149] = [];
    this.opcodes[149].opNext = 152;
    this.opcodes[149].type = ALT;

    this.opcodes[150] = [];
    this.opcodes[150].opNext = 151;
    this.opcodes[150].type = TLS;
    this.opcodes[150].length = 1;
    this.opcodes[150].stringIndex = 35;

    this.opcodes[151] = [];
    this.opcodes[151].opNext = 152;
    this.opcodes[151].type = TLS;
    this.opcodes[151].length = 1;
    this.opcodes[151].stringIndex = 36;

    this.opcodes[152] = [];
    this.opcodes[152].opNext = 155;
    this.opcodes[152].type = ALT;

    this.opcodes[153] = [];
    this.opcodes[153].opNext = 154;
    this.opcodes[153].type = TLS;
    this.opcodes[153].length = 1;
    this.opcodes[153].stringIndex = 37;

    this.opcodes[154] = [];
    this.opcodes[154].opNext = 155;
    this.opcodes[154].type = TLS;
    this.opcodes[154].length = 1;
    this.opcodes[154].stringIndex = 38;

    this.opcodes[155] = [];
    this.opcodes[155].opNext = 156;
    this.opcodes[155].type = RNM;
    this.opcodes[155].ruleIndex = 54;

    this.opcodes[156] = [];
    this.opcodes[156].opNext = 163;
    this.opcodes[156].type = CAT;

    this.opcodes[157] = [];
    this.opcodes[157].opNext = 158;
    this.opcodes[157].type = RNM;
    this.opcodes[157].ruleIndex = 29;

    this.opcodes[158] = [];
    this.opcodes[158].opNext = 159;
    this.opcodes[158].type = RNM;
    this.opcodes[158].ruleIndex = 53;

    this.opcodes[159] = [];
    this.opcodes[159].opNext = 163;
    this.opcodes[159].type = REP;
    this.opcodes[159].min = 0;
    this.opcodes[159].max = 1;

    this.opcodes[160] = [];
    this.opcodes[160].opNext = 163;
    this.opcodes[160].type = ALT;

    this.opcodes[161] = [];
    this.opcodes[161].opNext = 162;
    this.opcodes[161].type = RNM;
    this.opcodes[161].ruleIndex = 27;

    this.opcodes[162] = [];
    this.opcodes[162].opNext = 163;
    this.opcodes[162].type = RNM;
    this.opcodes[162].ruleIndex = 28;

    this.opcodes[163] = [];
    this.opcodes[163].opNext = 169;
    this.opcodes[163].type = REP;
    this.opcodes[163].min = 1;
    this.opcodes[163].max = Infinity;

    this.opcodes[164] = [];
    this.opcodes[164].opNext = 169;
    this.opcodes[164].type = CAT;

    this.opcodes[165] = [];
    this.opcodes[165].opNext = 166;
    this.opcodes[165].type = RNM;
    this.opcodes[165].ruleIndex = 53;

    this.opcodes[166] = [];
    this.opcodes[166].opNext = 167;
    this.opcodes[166].type = RNM;
    this.opcodes[166].ruleIndex = 23;

    this.opcodes[167] = [];
    this.opcodes[167].opNext = 168;
    this.opcodes[167].type = RNM;
    this.opcodes[167].ruleIndex = 53;

    this.opcodes[168] = [];
    this.opcodes[168].opNext = 169;
    this.opcodes[168].type = RNM;
    this.opcodes[168].ruleIndex = 29;

    this.opcodes[169] = [];
    this.opcodes[169].opNext = 175;
    this.opcodes[169].type = REP;
    this.opcodes[169].min = 1;
    this.opcodes[169].max = Infinity;

    this.opcodes[170] = [];
    this.opcodes[170].opNext = 175;
    this.opcodes[170].type = CAT;

    this.opcodes[171] = [];
    this.opcodes[171].opNext = 172;
    this.opcodes[171].type = RNM;
    this.opcodes[171].ruleIndex = 53;

    this.opcodes[172] = [];
    this.opcodes[172].opNext = 173;
    this.opcodes[172].type = RNM;
    this.opcodes[172].ruleIndex = 24;

    this.opcodes[173] = [];
    this.opcodes[173].opNext = 174;
    this.opcodes[173].type = RNM;
    this.opcodes[173].ruleIndex = 53;

    this.opcodes[174] = [];
    this.opcodes[174].opNext = 175;
    this.opcodes[174].type = RNM;
    this.opcodes[174].ruleIndex = 29;

    this.opcodes[175] = [];
    this.opcodes[175].opNext = 184;
    this.opcodes[175].type = ALT;

    this.opcodes[176] = [];
    this.opcodes[176].opNext = 177;
    this.opcodes[176].type = RNM;
    this.opcodes[176].ruleIndex = 30;

    this.opcodes[177] = [];
    this.opcodes[177].opNext = 178;
    this.opcodes[177].type = RNM;
    this.opcodes[177].ruleIndex = 34;

    this.opcodes[178] = [];
    this.opcodes[178].opNext = 184;
    this.opcodes[178].type = CAT;

    this.opcodes[179] = [];
    this.opcodes[179].opNext = 180;
    this.opcodes[179].type = TLS;
    this.opcodes[179].length = 1;
    this.opcodes[179].stringIndex = 39;

    this.opcodes[180] = [];
    this.opcodes[180].opNext = 181;
    this.opcodes[180].type = RNM;
    this.opcodes[180].ruleIndex = 53;

    this.opcodes[181] = [];
    this.opcodes[181].opNext = 182;
    this.opcodes[181].type = RNM;
    this.opcodes[181].ruleIndex = 26;

    this.opcodes[182] = [];
    this.opcodes[182].opNext = 183;
    this.opcodes[182].type = RNM;
    this.opcodes[182].ruleIndex = 53;

    this.opcodes[183] = [];
    this.opcodes[183].opNext = 184;
    this.opcodes[183].type = TLS;
    this.opcodes[183].length = 1;
    this.opcodes[183].stringIndex = 40;

    this.opcodes[184] = [];
    this.opcodes[184].opNext = 191;
    this.opcodes[184].type = CAT;

    this.opcodes[185] = [];
    this.opcodes[185].opNext = 186;
    this.opcodes[185].type = RNM;
    this.opcodes[185].ruleIndex = 33;

    this.opcodes[186] = [];
    this.opcodes[186].opNext = 187;
    this.opcodes[186].type = RNM;
    this.opcodes[186].ruleIndex = 53;

    this.opcodes[187] = [];
    this.opcodes[187].opNext = 191;
    this.opcodes[187].type = REP;
    this.opcodes[187].min = 0;
    this.opcodes[187].max = 1;

    this.opcodes[188] = [];
    this.opcodes[188].opNext = 191;
    this.opcodes[188].type = ALT;

    this.opcodes[189] = [];
    this.opcodes[189].opNext = 190;
    this.opcodes[189].type = RNM;
    this.opcodes[189].ruleIndex = 31;

    this.opcodes[190] = [];
    this.opcodes[190].opNext = 191;
    this.opcodes[190].type = RNM;
    this.opcodes[190].ruleIndex = 32;

    this.opcodes[191] = [];
    this.opcodes[191].opNext = 197;
    this.opcodes[191].type = REP;
    this.opcodes[191].min = 1;
    this.opcodes[191].max = Infinity;

    this.opcodes[192] = [];
    this.opcodes[192].opNext = 197;
    this.opcodes[192].type = CAT;

    this.opcodes[193] = [];
    this.opcodes[193].opNext = 194;
    this.opcodes[193].type = RNM;
    this.opcodes[193].ruleIndex = 53;

    this.opcodes[194] = [];
    this.opcodes[194].opNext = 195;
    this.opcodes[194].type = RNM;
    this.opcodes[194].ruleIndex = 23;

    this.opcodes[195] = [];
    this.opcodes[195].opNext = 196;
    this.opcodes[195].type = RNM;
    this.opcodes[195].ruleIndex = 53;

    this.opcodes[196] = [];
    this.opcodes[196].opNext = 197;
    this.opcodes[196].type = RNM;
    this.opcodes[196].ruleIndex = 33;

    this.opcodes[197] = [];
    this.opcodes[197].opNext = 203;
    this.opcodes[197].type = REP;
    this.opcodes[197].min = 1;
    this.opcodes[197].max = Infinity;

    this.opcodes[198] = [];
    this.opcodes[198].opNext = 203;
    this.opcodes[198].type = CAT;

    this.opcodes[199] = [];
    this.opcodes[199].opNext = 200;
    this.opcodes[199].type = RNM;
    this.opcodes[199].ruleIndex = 53;

    this.opcodes[200] = [];
    this.opcodes[200].opNext = 201;
    this.opcodes[200].type = RNM;
    this.opcodes[200].ruleIndex = 24;

    this.opcodes[201] = [];
    this.opcodes[201].opNext = 202;
    this.opcodes[201].type = RNM;
    this.opcodes[201].ruleIndex = 53;

    this.opcodes[202] = [];
    this.opcodes[202].opNext = 203;
    this.opcodes[202].type = RNM;
    this.opcodes[202].ruleIndex = 33;

    this.opcodes[203] = [];
    this.opcodes[203].opNext = 211;
    this.opcodes[203].type = ALT;

    this.opcodes[204] = [];
    this.opcodes[204].opNext = 205;
    this.opcodes[204].type = RNM;
    this.opcodes[204].ruleIndex = 35;

    this.opcodes[205] = [];
    this.opcodes[205].opNext = 211;
    this.opcodes[205].type = CAT;

    this.opcodes[206] = [];
    this.opcodes[206].opNext = 207;
    this.opcodes[206].type = TLS;
    this.opcodes[206].length = 1;
    this.opcodes[206].stringIndex = 41;

    this.opcodes[207] = [];
    this.opcodes[207].opNext = 208;
    this.opcodes[207].type = RNM;
    this.opcodes[207].ruleIndex = 53;

    this.opcodes[208] = [];
    this.opcodes[208].opNext = 209;
    this.opcodes[208].type = RNM;
    this.opcodes[208].ruleIndex = 30;

    this.opcodes[209] = [];
    this.opcodes[209].opNext = 210;
    this.opcodes[209].type = RNM;
    this.opcodes[209].ruleIndex = 53;

    this.opcodes[210] = [];
    this.opcodes[210].opNext = 211;
    this.opcodes[210].type = TLS;
    this.opcodes[210].length = 1;
    this.opcodes[210].stringIndex = 42;

    this.opcodes[211] = [];
    this.opcodes[211].opNext = 223;
    this.opcodes[211].type = CAT;

    this.opcodes[212] = [];
    this.opcodes[212].opNext = 218;
    this.opcodes[212].type = REP;
    this.opcodes[212].min = 0;
    this.opcodes[212].max = 1;

    this.opcodes[213] = [];
    this.opcodes[213].opNext = 218;
    this.opcodes[213].type = CAT;

    this.opcodes[214] = [];
    this.opcodes[214].opNext = 215;
    this.opcodes[214].type = TLS;
    this.opcodes[214].length = 1;
    this.opcodes[214].stringIndex = 43;

    this.opcodes[215] = [];
    this.opcodes[215].opNext = 216;
    this.opcodes[215].type = RNM;
    this.opcodes[215].ruleIndex = 36;

    this.opcodes[216] = [];
    this.opcodes[216].opNext = 217;
    this.opcodes[216].type = TLS;
    this.opcodes[216].length = 1;
    this.opcodes[216].stringIndex = 44;

    this.opcodes[217] = [];
    this.opcodes[217].opNext = 218;
    this.opcodes[217].type = RNM;
    this.opcodes[217].ruleIndex = 53;

    this.opcodes[218] = [];
    this.opcodes[218].opNext = 219;
    this.opcodes[218].type = TLS;
    this.opcodes[218].length = 1;
    this.opcodes[218].stringIndex = 45;

    this.opcodes[219] = [];
    this.opcodes[219].opNext = 220;
    this.opcodes[219].type = RNM;
    this.opcodes[219].ruleIndex = 53;

    this.opcodes[220] = [];
    this.opcodes[220].opNext = 221;
    this.opcodes[220].type = RNM;
    this.opcodes[220].ruleIndex = 30;

    this.opcodes[221] = [];
    this.opcodes[221].opNext = 222;
    this.opcodes[221].type = RNM;
    this.opcodes[221].ruleIndex = 53;

    this.opcodes[222] = [];
    this.opcodes[222].opNext = 223;
    this.opcodes[222].type = TLS;
    this.opcodes[222].length = 1;
    this.opcodes[222].stringIndex = 46;

    this.opcodes[223] = [];
    this.opcodes[223].opNext = 256;
    this.opcodes[223].type = CAT;

    this.opcodes[224] = [];
    this.opcodes[224].opNext = 230;
    this.opcodes[224].type = REP;
    this.opcodes[224].min = 0;
    this.opcodes[224].max = 1;

    this.opcodes[225] = [];
    this.opcodes[225].opNext = 230;
    this.opcodes[225].type = CAT;

    this.opcodes[226] = [];
    this.opcodes[226].opNext = 227;
    this.opcodes[226].type = TLS;
    this.opcodes[226].length = 1;
    this.opcodes[226].stringIndex = 47;

    this.opcodes[227] = [];
    this.opcodes[227].opNext = 228;
    this.opcodes[227].type = RNM;
    this.opcodes[227].ruleIndex = 36;

    this.opcodes[228] = [];
    this.opcodes[228].opNext = 229;
    this.opcodes[228].type = TLS;
    this.opcodes[228].length = 1;
    this.opcodes[228].stringIndex = 48;

    this.opcodes[229] = [];
    this.opcodes[229].opNext = 230;
    this.opcodes[229].type = RNM;
    this.opcodes[229].ruleIndex = 53;

    this.opcodes[230] = [];
    this.opcodes[230].opNext = 234;
    this.opcodes[230].type = REP;
    this.opcodes[230].min = 0;
    this.opcodes[230].max = 1;

    this.opcodes[231] = [];
    this.opcodes[231].opNext = 234;
    this.opcodes[231].type = CAT;

    this.opcodes[232] = [];
    this.opcodes[232].opNext = 233;
    this.opcodes[232].type = RNM;
    this.opcodes[232].ruleIndex = 41;

    this.opcodes[233] = [];
    this.opcodes[233].opNext = 234;
    this.opcodes[233].type = RNM;
    this.opcodes[233].ruleIndex = 53;

    this.opcodes[234] = [];
    this.opcodes[234].opNext = 238;
    this.opcodes[234].type = REP;
    this.opcodes[234].min = 0;
    this.opcodes[234].max = 1;

    this.opcodes[235] = [];
    this.opcodes[235].opNext = 238;
    this.opcodes[235].type = CAT;

    this.opcodes[236] = [];
    this.opcodes[236].opNext = 237;
    this.opcodes[236].type = RNM;
    this.opcodes[236].ruleIndex = 42;

    this.opcodes[237] = [];
    this.opcodes[237].opNext = 238;
    this.opcodes[237].type = RNM;
    this.opcodes[237].ruleIndex = 53;

    this.opcodes[238] = [];
    this.opcodes[238].opNext = 239;
    this.opcodes[238].type = RNM;
    this.opcodes[238].ruleIndex = 43;

    this.opcodes[239] = [];
    this.opcodes[239].opNext = 240;
    this.opcodes[239].type = RNM;
    this.opcodes[239].ruleIndex = 53;

    this.opcodes[240] = [];
    this.opcodes[240].opNext = 256;
    this.opcodes[240].type = ALT;

    this.opcodes[241] = [];
    this.opcodes[241].opNext = 245;
    this.opcodes[241].type = CAT;

    this.opcodes[242] = [];
    this.opcodes[242].opNext = 243;
    this.opcodes[242].type = RNM;
    this.opcodes[242].ruleIndex = 44;

    this.opcodes[243] = [];
    this.opcodes[243].opNext = 244;
    this.opcodes[243].type = RNM;
    this.opcodes[243].ruleIndex = 53;

    this.opcodes[244] = [];
    this.opcodes[244].opNext = 245;
    this.opcodes[244].type = RNM;
    this.opcodes[244].ruleIndex = 7;

    this.opcodes[245] = [];
    this.opcodes[245].opNext = 250;
    this.opcodes[245].type = CAT;

    this.opcodes[246] = [];
    this.opcodes[246].opNext = 247;
    this.opcodes[246].type = RNM;
    this.opcodes[246].ruleIndex = 45;

    this.opcodes[247] = [];
    this.opcodes[247].opNext = 248;
    this.opcodes[247].type = RNM;
    this.opcodes[247].ruleIndex = 53;

    this.opcodes[248] = [];
    this.opcodes[248].opNext = 249;
    this.opcodes[248].type = TLS;
    this.opcodes[248].length = 1;
    this.opcodes[248].stringIndex = 49;

    this.opcodes[249] = [];
    this.opcodes[249].opNext = 250;
    this.opcodes[249].type = RNM;
    this.opcodes[249].ruleIndex = 47;

    this.opcodes[250] = [];
    this.opcodes[250].opNext = 256;
    this.opcodes[250].type = CAT;

    this.opcodes[251] = [];
    this.opcodes[251].opNext = 252;
    this.opcodes[251].type = RNM;
    this.opcodes[251].ruleIndex = 46;

    this.opcodes[252] = [];
    this.opcodes[252].opNext = 253;
    this.opcodes[252].type = RNM;
    this.opcodes[252].ruleIndex = 53;

    this.opcodes[253] = [];
    this.opcodes[253].opNext = 254;
    this.opcodes[253].type = RNM;
    this.opcodes[253].ruleIndex = 63;

    this.opcodes[254] = [];
    this.opcodes[254].opNext = 255;
    this.opcodes[254].type = RNM;
    this.opcodes[254].ruleIndex = 48;

    this.opcodes[255] = [];
    this.opcodes[255].opNext = 256;
    this.opcodes[255].type = RNM;
    this.opcodes[255].ruleIndex = 63;

    this.opcodes[256] = [];
    this.opcodes[256].opNext = 260;
    this.opcodes[256].type = CAT;

    this.opcodes[257] = [];
    this.opcodes[257].opNext = 258;
    this.opcodes[257].type = RNM;
    this.opcodes[257].ruleIndex = 37;

    this.opcodes[258] = [];
    this.opcodes[258].opNext = 259;
    this.opcodes[258].type = RNM;
    this.opcodes[258].ruleIndex = 38;

    this.opcodes[259] = [];
    this.opcodes[259].opNext = 260;
    this.opcodes[259].type = RNM;
    this.opcodes[259].ruleIndex = 39;

    this.opcodes[260] = [];
    this.opcodes[260].opNext = 261;
    this.opcodes[260].type = RNM;
    this.opcodes[260].ruleIndex = 51;

    this.opcodes[261] = [];
    this.opcodes[261].opNext = 262;
    this.opcodes[261].type = TLS;
    this.opcodes[261].length = 2;
    this.opcodes[261].stringIndex = 50;

    this.opcodes[262] = [];
    this.opcodes[262].opNext = 265;
    this.opcodes[262].type = ALT;

    this.opcodes[263] = [];
    this.opcodes[263].opNext = 264;
    this.opcodes[263].type = RNM;
    this.opcodes[263].ruleIndex = 51;

    this.opcodes[264] = [];
    this.opcodes[264].opNext = 265;
    this.opcodes[264].type = RNM;
    this.opcodes[264].ruleIndex = 40;

    this.opcodes[265] = [];
    this.opcodes[265].opNext = 266;
    this.opcodes[265].type = TLS;
    this.opcodes[265].length = 1;
    this.opcodes[265].stringIndex = 52;

    this.opcodes[266] = [];
    this.opcodes[266].opNext = 267;
    this.opcodes[266].type = TLS;
    this.opcodes[266].length = 1;
    this.opcodes[266].stringIndex = 53;

    this.opcodes[267] = [];
    this.opcodes[267].opNext = 270;
    this.opcodes[267].type = ALT;

    this.opcodes[268] = [];
    this.opcodes[268].opNext = 269;
    this.opcodes[268].type = RNM;
    this.opcodes[268].ruleIndex = 18;

    this.opcodes[269] = [];
    this.opcodes[269].opNext = 270;
    this.opcodes[269].type = RNM;
    this.opcodes[269].ruleIndex = 17;

    this.opcodes[270] = [];
    this.opcodes[270].opNext = 273;
    this.opcodes[270].type = ALT;

    this.opcodes[271] = [];
    this.opcodes[271].opNext = 272;
    this.opcodes[271].type = RNM;
    this.opcodes[271].ruleIndex = 12;

    this.opcodes[272] = [];
    this.opcodes[272].opNext = 273;
    this.opcodes[272].type = RNM;
    this.opcodes[272].ruleIndex = 15;

    this.opcodes[273] = [];
    this.opcodes[273].opNext = 276;
    this.opcodes[273].type = ALT;

    this.opcodes[274] = [];
    this.opcodes[274].opNext = 275;
    this.opcodes[274].type = TLS;
    this.opcodes[274].length = 1;
    this.opcodes[274].stringIndex = 54;

    this.opcodes[275] = [];
    this.opcodes[275].opNext = 276;
    this.opcodes[275].type = TLS;
    this.opcodes[275].length = 2;
    this.opcodes[275].stringIndex = 55;

    this.opcodes[276] = [];
    this.opcodes[276].opNext = 283;
    this.opcodes[276].type = ALT;

    this.opcodes[277] = [];
    this.opcodes[277].opNext = 278;
    this.opcodes[277].type = TLS;
    this.opcodes[277].length = 1;
    this.opcodes[277].stringIndex = 57;

    this.opcodes[278] = [];
    this.opcodes[278].opNext = 279;
    this.opcodes[278].type = TLS;
    this.opcodes[278].length = 2;
    this.opcodes[278].stringIndex = 58;

    this.opcodes[279] = [];
    this.opcodes[279].opNext = 280;
    this.opcodes[279].type = TLS;
    this.opcodes[279].length = 2;
    this.opcodes[279].stringIndex = 60;

    this.opcodes[280] = [];
    this.opcodes[280].opNext = 281;
    this.opcodes[280].type = TLS;
    this.opcodes[280].length = 1;
    this.opcodes[280].stringIndex = 62;

    this.opcodes[281] = [];
    this.opcodes[281].opNext = 282;
    this.opcodes[281].type = TLS;
    this.opcodes[281].length = 2;
    this.opcodes[281].stringIndex = 63;

    this.opcodes[282] = [];
    this.opcodes[282].opNext = 283;
    this.opcodes[282].type = TLS;
    this.opcodes[282].length = 1;
    this.opcodes[282].stringIndex = 65;

    this.opcodes[283] = [];
    this.opcodes[283].opNext = 286;
    this.opcodes[283].type = ALT;

    this.opcodes[284] = [];
    this.opcodes[284].opNext = 285;
    this.opcodes[284].type = TLS;
    this.opcodes[284].length = 1;
    this.opcodes[284].stringIndex = 66;

    this.opcodes[285] = [];
    this.opcodes[285].opNext = 286;
    this.opcodes[285].type = TLS;
    this.opcodes[285].length = 2;
    this.opcodes[285].stringIndex = 67;

    this.opcodes[286] = [];
    this.opcodes[286].opNext = 294;
    this.opcodes[286].type = CAT;

    this.opcodes[287] = [];
    this.opcodes[287].opNext = 291;
    this.opcodes[287].type = REP;
    this.opcodes[287].min = 0;
    this.opcodes[287].max = 1;

    this.opcodes[288] = [];
    this.opcodes[288].opNext = 291;
    this.opcodes[288].type = ALT;

    this.opcodes[289] = [];
    this.opcodes[289].opNext = 290;
    this.opcodes[289].type = TLS;
    this.opcodes[289].length = 1;
    this.opcodes[289].stringIndex = 69;

    this.opcodes[290] = [];
    this.opcodes[290].opNext = 291;
    this.opcodes[290].type = TLS;
    this.opcodes[290].length = 1;
    this.opcodes[290].stringIndex = 70;

    this.opcodes[291] = [];
    this.opcodes[291].opNext = 294;
    this.opcodes[291].type = ALT;

    this.opcodes[292] = [];
    this.opcodes[292].opNext = 293;
    this.opcodes[292].type = RNM;
    this.opcodes[292].ruleIndex = 50;

    this.opcodes[293] = [];
    this.opcodes[293].opNext = 294;
    this.opcodes[293].type = RNM;
    this.opcodes[293].ruleIndex = 49;

    this.opcodes[294] = [];
    this.opcodes[294].opNext = 298;
    this.opcodes[294].type = REP;
    this.opcodes[294].min = 1;
    this.opcodes[294].max = Infinity;

    this.opcodes[295] = [];
    this.opcodes[295].opNext = 298;
    this.opcodes[295].type = ALT;

    this.opcodes[296] = [];
    this.opcodes[296].opNext = 297;
    this.opcodes[296].type = RNM;
    this.opcodes[296].ruleIndex = 69;

    this.opcodes[297] = [];
    this.opcodes[297].opNext = 298;
    this.opcodes[297].type = RNM;
    this.opcodes[297].ruleIndex = 70;

    this.opcodes[298] = [];
    this.opcodes[298].opNext = 304;
    this.opcodes[298].type = ALT;

    this.opcodes[299] = [];
    this.opcodes[299].opNext = 303;
    this.opcodes[299].type = CAT;

    this.opcodes[300] = [];
    this.opcodes[300].opNext = 301;
    this.opcodes[300].type = RNM;
    this.opcodes[300].ruleIndex = 67;

    this.opcodes[301] = [];
    this.opcodes[301].opNext = 303;
    this.opcodes[301].type = REP;
    this.opcodes[301].min = 0;
    this.opcodes[301].max = Infinity;

    this.opcodes[302] = [];
    this.opcodes[302].opNext = 303;
    this.opcodes[302].type = RNM;
    this.opcodes[302].ruleIndex = 65;

    this.opcodes[303] = [];
    this.opcodes[303].opNext = 304;
    this.opcodes[303].type = RNM;
    this.opcodes[303].ruleIndex = 66;

    this.opcodes[304] = [];
    this.opcodes[304].opNext = 309;
    this.opcodes[304].type = CAT;

    this.opcodes[305] = [];
    this.opcodes[305].opNext = 306;
    this.opcodes[305].type = RNM;
    this.opcodes[305].ruleIndex = 49;

    this.opcodes[306] = [];
    this.opcodes[306].opNext = 307;
    this.opcodes[306].type = TLS;
    this.opcodes[306].length = 1;
    this.opcodes[306].stringIndex = 71;

    this.opcodes[307] = [];
    this.opcodes[307].opNext = 309;
    this.opcodes[307].type = REP;
    this.opcodes[307].min = 1;
    this.opcodes[307].max = Infinity;

    this.opcodes[308] = [];
    this.opcodes[308].opNext = 309;
    this.opcodes[308].type = RNM;
    this.opcodes[308].ruleIndex = 65;

    this.opcodes[309] = [];
    this.opcodes[309].opNext = 315;
    this.opcodes[309].type = ALT;

    this.opcodes[310] = [];
    this.opcodes[310].opNext = 314;
    this.opcodes[310].type = CAT;

    this.opcodes[311] = [];
    this.opcodes[311].opNext = 312;
    this.opcodes[311].type = RNM;
    this.opcodes[311].ruleIndex = 67;

    this.opcodes[312] = [];
    this.opcodes[312].opNext = 314;
    this.opcodes[312].type = REP;
    this.opcodes[312].min = 0;
    this.opcodes[312].max = Infinity;

    this.opcodes[313] = [];
    this.opcodes[313].opNext = 314;
    this.opcodes[313].type = RNM;
    this.opcodes[313].ruleIndex = 65;

    this.opcodes[314] = [];
    this.opcodes[314].opNext = 315;
    this.opcodes[314].type = RNM;
    this.opcodes[314].ruleIndex = 66;

    this.opcodes[315] = [];
    this.opcodes[315].opNext = 319;
    this.opcodes[315].type = CAT;

    this.opcodes[316] = [];
    this.opcodes[316].opNext = 317;
    this.opcodes[316].type = RNM;
    this.opcodes[316].ruleIndex = 67;

    this.opcodes[317] = [];
    this.opcodes[317].opNext = 319;
    this.opcodes[317].type = REP;
    this.opcodes[317].min = 5;
    this.opcodes[317].max = 17;

    this.opcodes[318] = [];
    this.opcodes[318].opNext = 319;
    this.opcodes[318].type = RNM;
    this.opcodes[318].ruleIndex = 65;

    this.opcodes[319] = [];
    this.opcodes[319].opNext = 326;
    this.opcodes[319].type = REP;
    this.opcodes[319].min = 0;
    this.opcodes[319].max = Infinity;

    this.opcodes[320] = [];
    this.opcodes[320].opNext = 326;
    this.opcodes[320].type = ALT;

    this.opcodes[321] = [];
    this.opcodes[321].opNext = 322;
    this.opcodes[321].type = RNM;
    this.opcodes[321].ruleIndex = 59;

    this.opcodes[322] = [];
    this.opcodes[322].opNext = 323;
    this.opcodes[322].type = RNM;
    this.opcodes[322].ruleIndex = 60;

    this.opcodes[323] = [];
    this.opcodes[323].opNext = 324;
    this.opcodes[323].type = RNM;
    this.opcodes[323].ruleIndex = 61;

    this.opcodes[324] = [];
    this.opcodes[324].opNext = 325;
    this.opcodes[324].type = RNM;
    this.opcodes[324].ruleIndex = 62;

    this.opcodes[325] = [];
    this.opcodes[325].opNext = 326;
    this.opcodes[325].type = RNM;
    this.opcodes[325].ruleIndex = 55;

    this.opcodes[326] = [];
    this.opcodes[326].opNext = 333;
    this.opcodes[326].type = REP;
    this.opcodes[326].min = 1;
    this.opcodes[326].max = Infinity;

    this.opcodes[327] = [];
    this.opcodes[327].opNext = 333;
    this.opcodes[327].type = ALT;

    this.opcodes[328] = [];
    this.opcodes[328].opNext = 329;
    this.opcodes[328].type = RNM;
    this.opcodes[328].ruleIndex = 59;

    this.opcodes[329] = [];
    this.opcodes[329].opNext = 330;
    this.opcodes[329].type = RNM;
    this.opcodes[329].ruleIndex = 60;

    this.opcodes[330] = [];
    this.opcodes[330].opNext = 331;
    this.opcodes[330].type = RNM;
    this.opcodes[330].ruleIndex = 61;

    this.opcodes[331] = [];
    this.opcodes[331].opNext = 332;
    this.opcodes[331].type = RNM;
    this.opcodes[331].ruleIndex = 62;

    this.opcodes[332] = [];
    this.opcodes[332].opNext = 333;
    this.opcodes[332].type = RNM;
    this.opcodes[332].ruleIndex = 55;

    this.opcodes[333] = [];
    this.opcodes[333].opNext = 340;
    this.opcodes[333].type = CAT;

    this.opcodes[334] = [];
    this.opcodes[334].opNext = 335;
    this.opcodes[334].type = TLS;
    this.opcodes[334].length = 2;
    this.opcodes[334].stringIndex = 72;

    this.opcodes[335] = [];
    this.opcodes[335].opNext = 339;
    this.opcodes[335].type = REP;
    this.opcodes[335].min = 0;
    this.opcodes[335].max = Infinity;

    this.opcodes[336] = [];
    this.opcodes[336].opNext = 339;
    this.opcodes[336].type = ALT;

    this.opcodes[337] = [];
    this.opcodes[337].opNext = 338;
    this.opcodes[337].type = RNM;
    this.opcodes[337].ruleIndex = 56;

    this.opcodes[338] = [];
    this.opcodes[338].opNext = 339;
    this.opcodes[338].type = RNM;
    this.opcodes[338].ruleIndex = 57;

    this.opcodes[339] = [];
    this.opcodes[339].opNext = 340;
    this.opcodes[339].type = TLS;
    this.opcodes[339].length = 2;
    this.opcodes[339].stringIndex = 74;

    this.opcodes[340] = [];
    this.opcodes[340].opNext = 350;
    this.opcodes[340].type = ALT;

    this.opcodes[341] = [];
    this.opcodes[341].opNext = 342;
    this.opcodes[341].type = RNM;
    this.opcodes[341].ruleIndex = 59;

    this.opcodes[342] = [];
    this.opcodes[342].opNext = 343;
    this.opcodes[342].type = RNM;
    this.opcodes[342].ruleIndex = 60;

    this.opcodes[343] = [];
    this.opcodes[343].opNext = 344;
    this.opcodes[343].type = RNM;
    this.opcodes[343].ruleIndex = 61;

    this.opcodes[344] = [];
    this.opcodes[344].opNext = 345;
    this.opcodes[344].type = RNM;
    this.opcodes[344].ruleIndex = 62;

    this.opcodes[345] = [];
    this.opcodes[345].opNext = 346;
    this.opcodes[345].type = TRG;
    this.opcodes[345].min = 33;
    this.opcodes[345].max = 41;

    this.opcodes[346] = [];
    this.opcodes[346].opNext = 347;
    this.opcodes[346].type = TRG;
    this.opcodes[346].min = 43;
    this.opcodes[346].max = 126;

    this.opcodes[347] = [];
    this.opcodes[347].opNext = 348;
    this.opcodes[347].type = RNM;
    this.opcodes[347].ruleIndex = 71;

    this.opcodes[348] = [];
    this.opcodes[348].opNext = 349;
    this.opcodes[348].type = RNM;
    this.opcodes[348].ruleIndex = 72;

    this.opcodes[349] = [];
    this.opcodes[349].opNext = 350;
    this.opcodes[349].type = RNM;
    this.opcodes[349].ruleIndex = 73;

    this.opcodes[350] = [];
    this.opcodes[350].opNext = 353;
    this.opcodes[350].type = CAT;

    this.opcodes[351] = [];
    this.opcodes[351].opNext = 352;
    this.opcodes[351].type = TRG;
    this.opcodes[351].min = 42;
    this.opcodes[351].max = 42;

    this.opcodes[352] = [];
    this.opcodes[352].opNext = 353;
    this.opcodes[352].type = RNM;
    this.opcodes[352].ruleIndex = 58;

    this.opcodes[353] = [];
    this.opcodes[353].opNext = 363;
    this.opcodes[353].type = ALT;

    this.opcodes[354] = [];
    this.opcodes[354].opNext = 355;
    this.opcodes[354].type = RNM;
    this.opcodes[354].ruleIndex = 59;

    this.opcodes[355] = [];
    this.opcodes[355].opNext = 356;
    this.opcodes[355].type = RNM;
    this.opcodes[355].ruleIndex = 60;

    this.opcodes[356] = [];
    this.opcodes[356].opNext = 357;
    this.opcodes[356].type = RNM;
    this.opcodes[356].ruleIndex = 61;

    this.opcodes[357] = [];
    this.opcodes[357].opNext = 358;
    this.opcodes[357].type = RNM;
    this.opcodes[357].ruleIndex = 62;

    this.opcodes[358] = [];
    this.opcodes[358].opNext = 359;
    this.opcodes[358].type = TRG;
    this.opcodes[358].min = 33;
    this.opcodes[358].max = 46;

    this.opcodes[359] = [];
    this.opcodes[359].opNext = 360;
    this.opcodes[359].type = TRG;
    this.opcodes[359].min = 48;
    this.opcodes[359].max = 126;

    this.opcodes[360] = [];
    this.opcodes[360].opNext = 361;
    this.opcodes[360].type = RNM;
    this.opcodes[360].ruleIndex = 71;

    this.opcodes[361] = [];
    this.opcodes[361].opNext = 362;
    this.opcodes[361].type = RNM;
    this.opcodes[361].ruleIndex = 72;

    this.opcodes[362] = [];
    this.opcodes[362].opNext = 363;
    this.opcodes[362].type = RNM;
    this.opcodes[362].ruleIndex = 73;

    this.opcodes[363] = [];
    this.opcodes[363].opNext = 364;
    this.opcodes[363].type = TRG;
    this.opcodes[363].min = 32;
    this.opcodes[363].max = 32;

    this.opcodes[364] = [];
    this.opcodes[364].opNext = 365;
    this.opcodes[364].type = TRG;
    this.opcodes[364].min = 9;
    this.opcodes[364].max = 9;

    this.opcodes[365] = [];
    this.opcodes[365].opNext = 366;
    this.opcodes[365].type = TRG;
    this.opcodes[365].min = 13;
    this.opcodes[365].max = 13;

    this.opcodes[366] = [];
    this.opcodes[366].opNext = 367;
    this.opcodes[366].type = TRG;
    this.opcodes[366].min = 10;
    this.opcodes[366].max = 10;

    this.opcodes[367] = [];
    this.opcodes[367].opNext = 368;
    this.opcodes[367].type = TRG;
    this.opcodes[367].min = 34;
    this.opcodes[367].max = 34;

    this.opcodes[368] = [];
    this.opcodes[368].opNext = 369;
    this.opcodes[368].type = TRG;
    this.opcodes[368].min = 92;
    this.opcodes[368].max = 92;

    this.opcodes[369] = [];
    this.opcodes[369].opNext = 370;
    this.opcodes[369].type = TRG;
    this.opcodes[369].min = 48;
    this.opcodes[369].max = 57;

    this.opcodes[370] = [];
    this.opcodes[370].opNext = 371;
    this.opcodes[370].type = TRG;
    this.opcodes[370].min = 48;
    this.opcodes[370].max = 48;

    this.opcodes[371] = [];
    this.opcodes[371].opNext = 372;
    this.opcodes[371].type = TRG;
    this.opcodes[371].min = 49;
    this.opcodes[371].max = 57;

    this.opcodes[372] = [];
    this.opcodes[372].opNext = 378;
    this.opcodes[372].type = ALT;

    this.opcodes[373] = [];
    this.opcodes[373].opNext = 374;
    this.opcodes[373].type = TRG;
    this.opcodes[373].min = 33;
    this.opcodes[373].max = 123;

    this.opcodes[374] = [];
    this.opcodes[374].opNext = 375;
    this.opcodes[374].type = TRG;
    this.opcodes[374].min = 125;
    this.opcodes[374].max = 126;

    this.opcodes[375] = [];
    this.opcodes[375].opNext = 376;
    this.opcodes[375].type = RNM;
    this.opcodes[375].ruleIndex = 71;

    this.opcodes[376] = [];
    this.opcodes[376].opNext = 377;
    this.opcodes[376].type = RNM;
    this.opcodes[376].ruleIndex = 72;

    this.opcodes[377] = [];
    this.opcodes[377].opNext = 378;
    this.opcodes[377].type = RNM;
    this.opcodes[377].ruleIndex = 73;

    this.opcodes[378] = [];
    this.opcodes[378].opNext = 389;
    this.opcodes[378].type = ALT;

    this.opcodes[379] = [];
    this.opcodes[379].opNext = 380;
    this.opcodes[379].type = RNM;
    this.opcodes[379].ruleIndex = 59;

    this.opcodes[380] = [];
    this.opcodes[380].opNext = 381;
    this.opcodes[380].type = RNM;
    this.opcodes[380].ruleIndex = 60;

    this.opcodes[381] = [];
    this.opcodes[381].opNext = 382;
    this.opcodes[381].type = RNM;
    this.opcodes[381].ruleIndex = 61;

    this.opcodes[382] = [];
    this.opcodes[382].opNext = 383;
    this.opcodes[382].type = RNM;
    this.opcodes[382].ruleIndex = 62;

    this.opcodes[383] = [];
    this.opcodes[383].opNext = 384;
    this.opcodes[383].type = TRG;
    this.opcodes[383].min = 32;
    this.opcodes[383].max = 33;

    this.opcodes[384] = [];
    this.opcodes[384].opNext = 385;
    this.opcodes[384].type = TRG;
    this.opcodes[384].min = 35;
    this.opcodes[384].max = 91;

    this.opcodes[385] = [];
    this.opcodes[385].opNext = 386;
    this.opcodes[385].type = TRG;
    this.opcodes[385].min = 93;
    this.opcodes[385].max = 126;

    this.opcodes[386] = [];
    this.opcodes[386].opNext = 387;
    this.opcodes[386].type = RNM;
    this.opcodes[386].ruleIndex = 71;

    this.opcodes[387] = [];
    this.opcodes[387].opNext = 388;
    this.opcodes[387].type = RNM;
    this.opcodes[387].ruleIndex = 72;

    this.opcodes[388] = [];
    this.opcodes[388].opNext = 389;
    this.opcodes[388].type = RNM;
    this.opcodes[388].ruleIndex = 73;

    this.opcodes[389] = [];
    this.opcodes[389].opNext = 396;
    this.opcodes[389].type = ALT;

    this.opcodes[390] = [];
    this.opcodes[390].opNext = 393;
    this.opcodes[390].type = CAT;

    this.opcodes[391] = [];
    this.opcodes[391].opNext = 392;
    this.opcodes[391].type = RNM;
    this.opcodes[391].ruleIndex = 64;

    this.opcodes[392] = [];
    this.opcodes[392].opNext = 393;
    this.opcodes[392].type = RNM;
    this.opcodes[392].ruleIndex = 63;

    this.opcodes[393] = [];
    this.opcodes[393].opNext = 396;
    this.opcodes[393].type = CAT;

    this.opcodes[394] = [];
    this.opcodes[394].opNext = 395;
    this.opcodes[394].type = RNM;
    this.opcodes[394].ruleIndex = 64;

    this.opcodes[395] = [];
    this.opcodes[395].opNext = 396;
    this.opcodes[395].type = RNM;
    this.opcodes[395].ruleIndex = 64;

    this.opcodes[396] = [];
    this.opcodes[396].opNext = 399;
    this.opcodes[396].type = CAT;

    this.opcodes[397] = [];
    this.opcodes[397].opNext = 398;
    this.opcodes[397].type = TRG;
    this.opcodes[397].min = 194;
    this.opcodes[397].max = 223;

    this.opcodes[398] = [];
    this.opcodes[398].opNext = 399;
    this.opcodes[398].type = RNM;
    this.opcodes[398].ruleIndex = 74;

    this.opcodes[399] = [];
    this.opcodes[399].opNext = 416;
    this.opcodes[399].type = ALT;

    this.opcodes[400] = [];
    this.opcodes[400].opNext = 404;
    this.opcodes[400].type = CAT;

    this.opcodes[401] = [];
    this.opcodes[401].opNext = 402;
    this.opcodes[401].type = TRG;
    this.opcodes[401].min = 224;
    this.opcodes[401].max = 224;

    this.opcodes[402] = [];
    this.opcodes[402].opNext = 403;
    this.opcodes[402].type = TRG;
    this.opcodes[402].min = 160;
    this.opcodes[402].max = 191;

    this.opcodes[403] = [];
    this.opcodes[403].opNext = 404;
    this.opcodes[403].type = RNM;
    this.opcodes[403].ruleIndex = 74;

    this.opcodes[404] = [];
    this.opcodes[404].opNext = 408;
    this.opcodes[404].type = CAT;

    this.opcodes[405] = [];
    this.opcodes[405].opNext = 406;
    this.opcodes[405].type = TRG;
    this.opcodes[405].min = 225;
    this.opcodes[405].max = 236;

    this.opcodes[406] = [];
    this.opcodes[406].opNext = 408;
    this.opcodes[406].type = REP;
    this.opcodes[406].min = 2;
    this.opcodes[406].max = 2;

    this.opcodes[407] = [];
    this.opcodes[407].opNext = 408;
    this.opcodes[407].type = RNM;
    this.opcodes[407].ruleIndex = 74;

    this.opcodes[408] = [];
    this.opcodes[408].opNext = 412;
    this.opcodes[408].type = CAT;

    this.opcodes[409] = [];
    this.opcodes[409].opNext = 410;
    this.opcodes[409].type = TRG;
    this.opcodes[409].min = 237;
    this.opcodes[409].max = 237;

    this.opcodes[410] = [];
    this.opcodes[410].opNext = 411;
    this.opcodes[410].type = TRG;
    this.opcodes[410].min = 128;
    this.opcodes[410].max = 159;

    this.opcodes[411] = [];
    this.opcodes[411].opNext = 412;
    this.opcodes[411].type = RNM;
    this.opcodes[411].ruleIndex = 74;

    this.opcodes[412] = [];
    this.opcodes[412].opNext = 416;
    this.opcodes[412].type = CAT;

    this.opcodes[413] = [];
    this.opcodes[413].opNext = 414;
    this.opcodes[413].type = TRG;
    this.opcodes[413].min = 238;
    this.opcodes[413].max = 239;

    this.opcodes[414] = [];
    this.opcodes[414].opNext = 416;
    this.opcodes[414].type = REP;
    this.opcodes[414].min = 2;
    this.opcodes[414].max = 2;

    this.opcodes[415] = [];
    this.opcodes[415].opNext = 416;
    this.opcodes[415].type = RNM;
    this.opcodes[415].ruleIndex = 74;

    this.opcodes[416] = [];
    this.opcodes[416].opNext = 431;
    this.opcodes[416].type = ALT;

    this.opcodes[417] = [];
    this.opcodes[417].opNext = 422;
    this.opcodes[417].type = CAT;

    this.opcodes[418] = [];
    this.opcodes[418].opNext = 419;
    this.opcodes[418].type = TRG;
    this.opcodes[418].min = 240;
    this.opcodes[418].max = 240;

    this.opcodes[419] = [];
    this.opcodes[419].opNext = 420;
    this.opcodes[419].type = TRG;
    this.opcodes[419].min = 144;
    this.opcodes[419].max = 191;

    this.opcodes[420] = [];
    this.opcodes[420].opNext = 422;
    this.opcodes[420].type = REP;
    this.opcodes[420].min = 2;
    this.opcodes[420].max = 2;

    this.opcodes[421] = [];
    this.opcodes[421].opNext = 422;
    this.opcodes[421].type = RNM;
    this.opcodes[421].ruleIndex = 74;

    this.opcodes[422] = [];
    this.opcodes[422].opNext = 426;
    this.opcodes[422].type = CAT;

    this.opcodes[423] = [];
    this.opcodes[423].opNext = 424;
    this.opcodes[423].type = TRG;
    this.opcodes[423].min = 241;
    this.opcodes[423].max = 243;

    this.opcodes[424] = [];
    this.opcodes[424].opNext = 426;
    this.opcodes[424].type = REP;
    this.opcodes[424].min = 3;
    this.opcodes[424].max = 3;

    this.opcodes[425] = [];
    this.opcodes[425].opNext = 426;
    this.opcodes[425].type = RNM;
    this.opcodes[425].ruleIndex = 74;

    this.opcodes[426] = [];
    this.opcodes[426].opNext = 431;
    this.opcodes[426].type = CAT;

    this.opcodes[427] = [];
    this.opcodes[427].opNext = 428;
    this.opcodes[427].type = TRG;
    this.opcodes[427].min = 244;
    this.opcodes[427].max = 244;

    this.opcodes[428] = [];
    this.opcodes[428].opNext = 429;
    this.opcodes[428].type = TRG;
    this.opcodes[428].min = 128;
    this.opcodes[428].max = 143;

    this.opcodes[429] = [];
    this.opcodes[429].opNext = 431;
    this.opcodes[429].type = REP;
    this.opcodes[429].min = 2;
    this.opcodes[429].max = 2;

    this.opcodes[430] = [];
    this.opcodes[430].opNext = 431;
    this.opcodes[430].type = RNM;
    this.opcodes[430].ruleIndex = 74;

    this.opcodes[431] = [];
    this.opcodes[431].opNext = 432;
    this.opcodes[431].type = TRG;
    this.opcodes[431].min = 128;
    this.opcodes[431].max = 191;

}